-- Upgrade to v0.0.1 - the original schema, as it existed before any file
-- under assets/db/upgrade/ (i.e. before 1.0.0/1.sql). Lets the migration
-- runner (server/src/migrate/index.ts) build a database from nothing: every
-- other file here is incremental and assumes tables this one creates.
-- (New installs on a database already seeded via databaseSchema.sql skip
-- this file too - see LEGACY_CHECKS in the runner for how.)

CREATE TABLE app_languages
(
    code CHAR(2) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO app_languages (code, name)
VALUES ('ca', 'Catalan'),
       ('en', 'English'),
       ('es', 'Spanish'),
       ('it', 'Italian');

CREATE TABLE app_labels
(
    code     VARCHAR(50)  NOT NULL,
    language CHAR(2),
    text     VARCHAR(500) NOT NULL,
    PRIMARY KEY (code, language),
    FOREIGN KEY (language) REFERENCES app_languages (code) ON DELETE CASCADE
);

-- english labels
INSERT INTO app_labels (language, code, text)
VALUES ('en', 'ADD_BOOK', 'Add book'),
       ('en', 'ADD_BOOK_MANUALLY', 'Add book manually'),
       ('en', 'STOCK_CODE', 'Stock code'),
       ('en', 'CODE', 'Code'),
       ('en', 'STOCKS', 'Stocks'),
       ('en', 'CLOSE', 'Close'),
       ('en', 'DELETE', 'Delete'),
       ('en', 'CANCEL', 'Cancel'),
       ('en', 'SAVE', 'Save'),
       ('en', 'ADD', 'Add'),
       ('en', 'UPDATE', 'Update'),
       ('en', 'ACTIONS', 'Actions'),
       ('en', 'ADD_AND_PRINT', 'Add & print'),
       ('en', 'PRINT_QUEUE', 'Printer queue'),
       ('en', 'TOTAL_LABELS_TO_PRINT', 'Total labels to print:'),
       ('en', 'CLEAR_QUEUE', 'Clear queue'),
       ('en', 'PRINT', 'Print'),
       ('en', 'SNACKBAR_PRINT_LABEL_ALREADY_ADDED', 'Label already added into the queue'),
       ('en', 'SNACKBAR_PRINT_LABEL_ADDED', 'Label added into the queue'),
       ('en', 'SEARCH_BOOKS', 'Search books'),
       ('en', 'DASHBOARD', 'Dashboard'),
       ('en', 'LIBRARY', 'Library'),
       ('en', 'IMAGE', 'Image'),
       ('en', 'LOCATIONS', 'Locations'),
       ('en', 'LOCATION', 'Location'),
       ('en', 'NO_LOCATION', '[No location]'),
       ('en', 'CATEGORIES', 'Categories'),
       ('en', 'CATEGORY', 'Category'),
       ('en', 'CUSTOMERS', 'Customers'),
       ('en', 'AUTHORS', 'Authors'),
       ('en', 'SETTINGS', 'Settings'),
       ('en', 'LOG_OUT', 'Log out'),
       ('en', 'SCAN_BARCODE', 'Scan barcode'),
       ('en', 'ERROR_OCCURRED', 'An error has occurred'),
       ('en', 'SNACKBAR_NEW_AUTHOR_ADDED', 'New author added:'),
       ('en', 'SNACKBAR_AUTHOR_DELETED', 'Author has been deleted successfully'),
       ('en', 'BOOK', 'Book'),
       ('en', 'SNACKBAR_NEW_CATEGORY_ADDED', 'Category was been added successfully'),
       ('en', 'SNACKBAR_DELETED_CATEGORY', 'Category was been deleted successfully'),
       ('en', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'Customer has been added successfully'),
       ('en', 'SNACKBAR_DELETED_CUSTOMER', 'Customer has been deleted successfully'),
       ('en', 'SNACKBAR_NEW_LOCATION_ADDED', 'Location has been added successfully'),
       ('en', 'SNACKBAR_LOCATION_UPDATED', 'Location has been updated successfully'),
       ('en', 'SNACKBAR_DELETED_LOCATION', 'Location has been deleted successfully'),
       ('en', 'SNACKBAR_AUTHOR_UPDATED', 'Author updated successfully'),
       ('en', 'SNACKBAR_BOOK_STOCK_ADDED', 'Book stock has been added'),
       ('en', 'SNACKBAR_BOOK_STOCK_DELETED', 'Book stock deleted successfully'),
       ('en', 'SNACKBAR_BOOK_STOCK_UPDATED', 'Book stock updated successfully'),
       ('en', 'SNACKBAR_BOOK_UPDATED', 'Book updated successfully'),
       ('en', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'Book image has been changed'),
       ('en', 'SNACKBAR_BOOK_DELETED', 'Book has been deleted'),
       ('en', 'BOOKED', 'Booked'),
       ('en', 'AVAILABLE', 'Available'),
       ('en', 'NOT_AVAILABLE', 'Not available'),
       ('en', 'DAMAGE', 'Damage'),
       ('en', 'SNACKBAR_CATEGORY_UPDATED', 'Category was updated successfully'),
       ('en', 'SNACKBAR_PROFILE_UPDATED', 'Profile information updated successfully'),
       ('en', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'Profile image has been removed successfully'),
       ('en', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'Profile image has been updated successfully'),
       ('en', 'EDIT_AUTHOR', 'Edit author'),
       ('en', 'ADD_AUTHOR', 'Add author'),
       ('en', 'NAME', 'Name'),
       ('en', 'DELETE_AUTHOR_TITLE', 'Delete author '),
       ('en', 'DELETE_AUTHOR_DESC', 'Are you sure that you want to remove this author?'),
       ('en', 'IMAGE_DRAG_AND_DROP', 'Drag and drop an image'),
       ('en', 'BOOK_HOVER_INFO', '(Hover to change book image)'),
       ('en', 'EDIT_BOOK_STOCK', 'Edit book stock'),
       ('en', 'OVERVIEW', 'Overview'),
       ('en', 'BOOKED_BOOKS', 'Booked books'),
       ('en', 'ADD_BOOK_STOCK', 'Add book stock'),
       ('en', 'BOOK_HAS_BEEN_ADDED', 'Book "{{name}" has been added'),
       ('en', 'ONLY_IMAGES_ALLOWED', 'Only images are allowed'),
       ('en', 'BOOK_STOCK_INFO',        'Book stock represents individual copies of a book, allowing you to track quantity and status. Each book stock has a unique barcode for identification. Please ensure the stock barcode is added to the book.'),
       ('en', 'BOOK_STOCK_STATUS', 'Status'),
       ('en', 'BOOKED_BY', 'Booked by'),
       ('en', 'DELETE_STOCK', 'Delete stock'),
       ('en', 'DELETE_STOCK_DESC', 'Are you sure that you want to remove this book stock?'),
       ('en', 'LANGUAGE', 'Language'),
       ('en', 'FORMAT', 'Format'),
       ('en', 'PAGES', 'Pages'),
       ('en', 'PUBLISHER', 'Publisher'),
       ('en', 'PUBLISHED_DATE', 'Published date'),
       ('en', 'DESCRIPTION', 'Description'),
       ('en', 'DELETE_BOOK', 'Delete book '),
       ('en', 'DELETE_BOOK_DESC', 'Are you sure that you want to delete this book?'),
       ('en', 'FULLSCREEN', 'Fullscreen'),
       ('en', 'EXIT_FULLSCREEN', 'Exit fullscreen'),
       ('en', 'DELETE_CATEGORY', 'Delete category '),
       ('en', 'DELETE_CATEGORY_DESC', 'Are you sure that you want to remove this category ?'),
       ('en', 'ADD_A_BOOK', 'Add a Book'),
       ('en', 'REMOVE_BOOK', 'Remove book'),
       ('en', 'REMOVE_BOOK_DESC', 'Are you sure that you want to remove this book from this customer ?'),
       ('en', 'EDIT_CUSTOMER', 'Edit customer'),
       ('en', 'ADD_CUSTOMER', 'Add customer'),
       ('en', 'TOTAL_BOOKS', 'Total books'),
       ('en', 'DELETE_CUSTOMER', 'Delete customer '),
       ('en', 'DELETE_CUSTOMER_DESC', 'Are you sure that you want to remove this customer?'),
       ('en', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Books Added Over Time'),
       ('en', 'DASHBOARD_TOTAL', 'Total'),
       ('en', 'RETURN_BOOKS', 'Return books'),
       ('en', 'SNACKBAR_RETURN_BOOKS', 'Books has been returned successfully'),
       ('en', 'RETURN', 'Return'),
       ('en', 'DASHBOARD_CHART', 'Chart'),
       ('en', 'DASHBOARD_LAST_BOOKS', 'Last books'),
       ('en', 'EDIT_LOCATION', 'Edit location'),
       ('en', 'ADD_LOCATION', 'Add location'),
       ('en', 'DELETE_LOCATION', 'Delete location '),
       ('en', 'DELETE_LOCATION_DESC', 'Are you sure that you want to remove this location ?'),
       ('en', 'NOT_FOUND_DESC', 'The page was not found.'),
       ('en', 'NOT_FOUND_GO_HOME', 'Go to home'),
       ('en', 'ADD_BOOK_ISBN', 'Add book (ISBN)'),
       ('en', 'ADD_BOOK_ISBN_DESC',        'Easily add a book to your library by entering its ISBN code. The app will automatically fetch the book''s details, including title, author, description, and more, and seamlessly add it to your collection.'),
       ('en', 'ISBN_CODE', 'ISBN code'),
       ('en', 'INVALID_ISBN_CODE', 'Invalid ISBN format. Please enter a valid ISBN-10 or ISBN-13.'),
       ('en', 'DRAG_AND_DROP_BOOK_COVER', 'Drag and drop book cover'),
       ('en', 'USERCONF_CHANGE_PASSWORD', 'Change password'),
       ('en', 'USERCONF_CURRENT_PASSWORD', 'Current password'),
       ('en', 'USERCONF_NEW_PASSWORD', 'New password'),
       ('en', 'USERCONF_MY_PROFILE', 'My profile'),
       ('en', 'USERCONF_PASSWORD_SECURITY', 'Please add all necessary characters to create safe password.'),
       ('en', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'At least 8 characters'),
       ('en', 'USERCONF_PASSWORD_UPPERCASE', 'At least one uppercase letter'),
       ('en', 'USERCONF_PASSWORD_ONE_NUMBER', 'At least one number'),
       ('en', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'At least one special character'),
       ('en', 'USEERCONF_PASSWORD_REPEAT', 'Repeat new password'),
       ('en', 'USERCONF_PASSWORD_NOT_MATCH', 'Passwords do not match!'),
       ('en', 'USERCONF_PASSWORD_CHANGED', 'Password changed successfully'),
       ('en', 'USERCONF_CHANGE_IMAGE', 'Change image'),
       ('en', 'USERCONF_REMOVE_IMAGE', 'Remove image'),
       ('en', 'USERCONF_IMAGE_SUPPORT', 'We only support PNGs, JPGs under 2MB'),
       ('en', 'USERCONF_NAME', 'Name'),
       ('en', 'USERCONF_LANGUAGE_REGION', 'Language & Region'),
       ('en', 'USERCONF_LANGUAGE', 'Language'),
       ('en', 'USERCONF_REGION', 'Region'),
       ('en', 'USERCONF_ACCOUNT_SECURITY', 'Account Security'),
       ('en', 'USERCONF_EMAIL', 'Email'),
       ('en', 'USERCONF_CHANGE_PASSWORD_DESC',      'Update your account password to keep your account secure. You’ll need to enter your current password and choose a new one that meets security requirements.'),
       ('en', 'USERCONF_DELETE_DESC', 'Permanently delete the account and remove workspace and books.'),
       ('en', 'USERCONF_DELETE', 'Delete account'),
       ('en', 'USERCONF_DELETE_USER_TITLE', 'Delete user'),
       ('en', 'USERCONF_DELETE_USER_DESC',       'Are you sure you want to delete your Paper Books" account? This will permanently remove your account and all associated content.'),
       ('en', 'USERCONF_IMAGE_FORMAT_ALERT', 'Please upload a PNG or JPEG image.'),
       ('en', 'EDIT_CATEGORY', 'Edit category'),
       ('en', 'ADD_CATEGORY', 'Add category'),
       ('en', 'USERCONF_IMAGE_SIZE_ALERT', 'File size must be less than 2MB'),
       ('en', 'ADD_FILTER', 'Add filter'),
       ('en', 'NO_STOCK_FILTER', 'No stock'),
       ('en', 'HAS_STOCK_FILTER', 'Has stock');

-- catalan labels
INSERT INTO app_labels (language, code, text)
VALUES ('ca', 'ADD_BOOK', 'Afegir llibre'),
       ('ca', 'ADD_BOOK_MANUALLY', 'Afegir llibre manualment'),
       ('ca', 'STOCK_CODE', 'Codi d’estoc'),
       ('ca', 'CODE', 'Codi'),
       ('ca', 'STOCKS', 'Estocs'),
       ('ca', 'CLOSE', 'Tancar'),
       ('ca', 'DELETE', 'Esborrar'),
       ('ca', 'CANCEL', 'Cancel·lar'),
       ('ca', 'SAVE', 'Desar'),
       ('ca', 'ADD', 'Afegir'),
       ('ca', 'UPDATE', 'Actualitzar'),
       ('ca', 'ACTIONS', 'Accions'),
       ('ca', 'ADD_AND_PRINT', 'Afegir i imprimir'),
       ('ca', 'PRINT_QUEUE', 'Cua d’impressió'),
       ('ca', 'TOTAL_LABELS_TO_PRINT', 'Total d’etiquetes a imprimir:'),
       ('ca', 'CLEAR_QUEUE', 'Buida la cua'),
       ('ca', 'PRINT', 'Imprimeix'),
       ('ca', 'SNACKBAR_PRINT_LABEL_ALREADY_ADDED', 'L’etiqueta ja s’ha afegit a la cua'),
       ('ca', 'SNACKBAR_PRINT_LABEL_ADDED', 'Etiqueta afegida a la cua'),
       ('ca', 'SEARCH_BOOKS', 'Cercar llibres'),
       ('ca', 'DASHBOARD', 'Panell de control'),
       ('ca', 'LIBRARY', 'Biblioteca'),
       ('ca', 'IMAGE', 'Imatge'),
       ('ca', 'LOCATIONS', 'Ubicacions'),
       ('ca', 'LOCATION', 'Ubicació'),
       ('ca', 'NO_LOCATION', '[Sense ubicació]'),
       ('ca', 'CATEGORIES', 'Categories'),
       ('ca', 'CATEGORY', 'Categoria'),
       ('ca', 'CUSTOMERS', 'Clients'),
       ('ca', 'AUTHORS', 'Autors'),
       ('ca', 'SETTINGS', 'Configuració'),
       ('ca', 'LOG_OUT', 'Tancar sessió'),
       ('ca', 'SCAN_BARCODE', 'Escanejar codi de barres'),
       ('ca', 'ERROR_OCCURRED', 'S’ha produït un error'),
       ('ca', 'SNACKBAR_NEW_AUTHOR_ADDED', 'Nou autor afegit:'),
       ('ca', 'SNACKBAR_AUTHOR_DELETED', 'L’autor s’ha eliminat correctament'),
       ('ca', 'BOOK', 'Llibre'),
       ('ca', 'SNACKBAR_NEW_CATEGORY_ADDED', 'La categoria s’ha afegit correctament'),
       ('ca', 'SNACKBAR_DELETED_CATEGORY', 'La categoria s’ha eliminat correctament'),
       ('ca', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'El client s’ha afegit correctament'),
       ('ca', 'SNACKBAR_DELETED_CUSTOMER', 'El client s’ha eliminat correctament'),
       ('ca', 'SNACKBAR_NEW_LOCATION_ADDED', 'L’ubicació s’ha afegit correctament'),
       ('ca', 'SNACKBAR_LOCATION_UPDATED', 'L’ubicació s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_DELETED_LOCATION', 'L’ubicació s’ha eliminat correctament'),
       ('ca', 'SNACKBAR_AUTHOR_UPDATED', 'L’autor s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_BOOK_STOCK_ADDED', 'S’ha afegit l’estoc del llibre'),
       ('ca', 'SNACKBAR_BOOK_STOCK_DELETED', 'L’estoc del llibre s’ha eliminat correctament'),
       ('ca', 'SNACKBAR_BOOK_STOCK_UPDATED', 'L’estoc del llibre s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_BOOK_UPDATED', 'El llibre s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'S’ha canviat la imatge del llibre'),
       ('ca', 'SNACKBAR_BOOK_DELETED', 'El llibre s’ha eliminat'),
       ('ca', 'BOOKED', 'Reservat'),
       ('ca', 'AVAILABLE', 'Disponible'),
       ('ca', 'NOT_AVAILABLE', 'No disponible'),
       ('ca', 'DAMAGE', 'Dany'),
       ('ca', 'SNACKBAR_CATEGORY_UPDATED', 'La categoria s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_PROFILE_UPDATED', 'La informació del perfil s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'La imatge del perfil s’ha eliminat correctament'),
       ('ca', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'La imatge del perfil s’ha actualitzat correctament'),
       ('ca', 'EDIT_AUTHOR', 'Editar autor'),
       ('ca', 'ADD_AUTHOR', 'Afegir autor'),
       ('ca', 'NAME', 'Nom'),
       ('ca', 'DELETE_AUTHOR_TITLE', 'Eliminar autor '),
       ('ca', 'DELETE_AUTHOR_DESC', 'Segur que voleu eliminar aquest autor?'),
       ('ca', 'IMAGE_DRAG_AND_DROP', 'Arrossega i deixa anar una imatge'),
       ('ca', 'BOOK_HOVER_INFO', '(Passeu el cursor per canviar la imatge del llibre)'),
       ('ca', 'EDIT_BOOK_STOCK', 'Editar estoc del llibre'),
       ('ca', 'OVERVIEW', 'Visió general'),
       ('ca', 'BOOKED_BOOKS', 'Llibres en préstec'),
       ('ca', 'ADD_BOOK_STOCK', 'Afegir estoc del llibre'),
       ('ca', 'BOOK_HAS_BEEN_ADDED', 'El llibre "{{name}}" s’ha afegit'),
       ('ca', 'ONLY_IMAGES_ALLOWED', 'Només es permeten imatges'),
       ('ca', 'BOOK_STOCK_INFO', 'L’estoc del llibre representa còpies individuals d’un llibre, permetent controlar la quantitat i l’estat. Cada estoc té un codi de barres únic per a la identificació. Assegureu-vos d’afegir el codi de barres a la fitxa del llibre.'),
       ('ca', 'BOOK_STOCK_STATUS', 'Estat'),
       ('ca', 'BOOKED_BY', 'Reservat per'),
       ('ca', 'DELETE_STOCK', 'Eliminar estoc'),
       ('ca', 'DELETE_STOCK_DESC', 'Segur que voleu eliminar aquest estoc del llibre?'),
       ('ca', 'LANGUAGE', 'Idioma'),
       ('ca', 'FORMAT', 'Format'),
       ('ca', 'PAGES', 'Pàgines'),
       ('ca', 'PUBLISHER', 'Editorial'),
       ('ca', 'PUBLISHED_DATE', 'Data de publicació'),
       ('ca', 'DESCRIPTION', 'Descripció'),
       ('ca', 'DELETE_BOOK', 'Eliminar llibre '),
       ('ca', 'DELETE_BOOK_DESC', 'Segur que voleu eliminar aquest llibre?'),
       ('ca', 'FULLSCREEN', 'Pantalla completa'),
       ('ca', 'EXIT_FULLSCREEN', 'Sortir de pantalla completa'),
       ('ca', 'DELETE_CATEGORY', 'Eliminar categoria '),
       ('ca', 'DELETE_CATEGORY_DESC', 'Segur que voleu eliminar aquesta categoria?'),
       ('ca', 'ADD_A_BOOK', 'Afegir un llibre'),
       ('ca', 'REMOVE_BOOK', 'Eliminar llibre'),
       ('ca', 'REMOVE_BOOK_DESC', 'Segur que voleu eliminar aquest llibre d’aquest client?'),
       ('ca', 'EDIT_CUSTOMER', 'Editar client'),
       ('ca', 'ADD_CUSTOMER', 'Afegir client'),
       ('ca', 'TOTAL_BOOKS', 'Total de llibres'),
       ('ca', 'DELETE_CUSTOMER', 'Eliminar client '),
       ('ca', 'DELETE_CUSTOMER_DESC', 'Segur que voleu eliminar aquest client?'),
       ('ca', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Llibres afegits al llarg del temps'),
       ('ca', 'DASHBOARD_TOTAL', 'Total'),
       ('ca', 'RETURN_BOOKS', 'Retornar llibres'),
       ('ca', 'SNACKBAR_RETURN_BOOKS', 'Els llibres s’han tornat correctament'),
       ('ca', 'RETURN', 'Retornar'),
       ('ca', 'DASHBOARD_CHART', 'Gràfic'),
       ('ca', 'DASHBOARD_LAST_BOOKS', 'Últims llibres'),
       ('ca', 'EDIT_LOCATION', 'Editar ubicació'),
       ('ca', 'ADD_LOCATION', 'Afegir ubicació'),
       ('ca', 'DELETE_LOCATION', 'Eliminar ubicació '),
       ('ca', 'DELETE_LOCATION_DESC', 'Segur que voleu eliminar aquesta ubicació?'),
       ('ca', 'NOT_FOUND_DESC', 'No s’ha trobat la pàgina.'),
       ('ca', 'NOT_FOUND_GO_HOME', 'Anar a l’inici'),
       ('ca', 'ADD_BOOK_ISBN', 'Afegir llibre (ISBN)'),
       ('ca', 'ADD_BOOK_ISBN_DESC', 'Afegiu fàcilment un llibre a la vostra biblioteca introduint el codi ISBN. L’aplicació recuperarà automàticament les dades del llibre, inclòs títol, autor, descripció i més, i l’afegirà a la vostra col·lecció.'),
       ('ca', 'ISBN_CODE', 'Codi ISBN'),
       ('ca', 'INVALID_ISBN_CODE', 'Format ISBN invàlid. Introduïu un ISBN-10 o ISBN-13 vàlid.'),
       ('ca', 'DRAG_AND_DROP_BOOK_COVER', 'Arrossega i deixa anar la coberta del llibre'),
       ('ca', 'USERCONF_CHANGE_PASSWORD', 'Canviar contrasenya'),
       ('ca', 'USERCONF_CURRENT_PASSWORD', 'Contrasenya actual'),
       ('ca', 'USERCONF_NEW_PASSWORD', 'Nova contrasenya'),
       ('ca', 'USERCONF_MY_PROFILE', 'El meu perfil'),
       ('ca', 'USERCONF_PASSWORD_SECURITY', 'Afegiu tots els caràcters necessaris per crear una contrasenya segura.'),
       ('ca', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'Almenys 8 caràcters'),
       ('ca', 'USERCONF_PASSWORD_UPPERCASE', 'Almenys una lletra majúscula'),
       ('ca', 'USERCONF_PASSWORD_ONE_NUMBER', 'Almenys un número'),
       ('ca', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'Almenys un caràcter especial'),
       ('ca', 'USEERCONF_PASSWORD_REPEAT', 'Repetiu la nova contrasenya'),
       ('ca', 'USERCONF_PASSWORD_NOT_MATCH', 'Les contrasenyes no coincideixen!'),
       ('ca', 'USERCONF_PASSWORD_CHANGED', 'Contrasenya canviada correctament'),
       ('ca', 'USERCONF_CHANGE_IMAGE', 'Canviar imatge'),
       ('ca', 'USERCONF_REMOVE_IMAGE', 'Eliminar imatge'),
       ('ca', 'USERCONF_IMAGE_SUPPORT', 'Només es suporten PNG i JPG de menys de 2 MB'),
       ('ca', 'USERCONF_NAME', 'Nom'),
       ('ca', 'USERCONF_LANGUAGE_REGION', 'Idioma i regió'),
       ('ca', 'USERCONF_LANGUAGE', 'Idioma'),
       ('ca', 'USERCONF_REGION', 'Regió'),
       ('ca', 'USERCONF_ACCOUNT_SECURITY', 'Seguretat del compte'),
       ('ca', 'USERCONF_EMAIL', 'Correu electrònic'),
       ('ca', 'USERCONF_CHANGE_PASSWORD_DESC', 'Actualitzeu la contrasenya del compte per mantenir-lo segur. Haureu d’introduir la contrasenya actual i triar-ne una de nova que compleixi els requisits de seguretat.'),
       ('ca', 'USERCONF_DELETE_DESC', 'Eliminar permanentment el compte i eliminar l’espai de treball i els llibres.'),
       ('ca', 'USERCONF_DELETE', 'Eliminar compte'),
       ('ca', 'USERCONF_DELETE_USER_TITLE', 'Eliminar usuari'),
       ('ca', 'USERCONF_DELETE_USER_DESC', 'Segur que voleu eliminar el vostre compte de Paper Books? Això eliminarà permanentment el compte i tot el contingut associat.'),
       ('ca', 'USERCONF_IMAGE_FORMAT_ALERT', 'Si us plau, pengeu una imatge PNG o JPEG.'),
       ('ca', 'EDIT_CATEGORY', 'Editar categoria'),
       ('ca', 'ADD_CATEGORY', 'Afegir categoria'),
       ('ca', 'USERCONF_IMAGE_SIZE_ALERT', 'La mida del fitxer ha de ser inferior a 2 MB'),
       ('ca', 'ADD_FILTER', 'Afegir filtre'),
       ('ca', 'NO_STOCK_FILTER', 'Sense estoc'),
       ('ca', 'HAS_STOCK_FILTER', 'Amb estoc');

-- spanish labels
INSERT INTO app_labels (language, code, text)
VALUES ('es', 'ADD_BOOK', 'Agregar libro'),
       ('es', 'ADD_BOOK_MANUALLY', 'Agregar libro manualmente'),
       ('es', 'STOCK_CODE', 'Código de stock'),
       ('es', 'CODE', 'Código'),
       ('es', 'STOCKS', 'Stocks'),
       ('es', 'CLOSE', 'Cerrar'),
       ('es', 'DELETE', 'Eliminar'),
       ('es', 'CANCEL', 'Cancelar'),
       ('es', 'SAVE', 'Guardar'),
       ('es', 'ADD', 'Agregar'),
       ('es', 'UPDATE', 'Actualizar'),
       ('es', 'ACTIONS', 'Acciones'),
       ('es', 'ADD_AND_PRINT', 'Agregar e imprimir'),
       ('es', 'PRINT_QUEUE', 'Cola de impresión'),
       ('es', 'TOTAL_LABELS_TO_PRINT', 'Total de etiquetas a imprimir:'),
       ('es', 'CLEAR_QUEUE', 'Vaciar la cola'),
       ('es', 'PRINT', 'Imprimir'),
       ('es', 'SNACKBAR_PRINT_LABEL_ALREADY_ADDED', 'La etiqueta ya se ha añadido a la cola'),
       ('es', 'SNACKBAR_PRINT_LABEL_ADDED', 'Etiqueta añadida a la cola'),
       ('es', 'SEARCH_BOOKS', 'Buscar libros'),
       ('es', 'DASHBOARD', 'Panel de control'),
       ('es', 'LIBRARY', 'Biblioteca'),
       ('es', 'IMAGE', 'Imagen'),
       ('es', 'LOCATIONS', 'Ubicaciones'),
       ('es', 'LOCATION', 'Ubicación'),
       ('es', 'NO_LOCATION', '[Sin ubicación]'),
       ('es', 'CATEGORIES', 'Categorías'),
       ('es', 'CATEGORY', 'Categoría'),
       ('es', 'CUSTOMERS', 'Clientes'),
       ('es', 'AUTHORS', 'Autores'),
       ('es', 'SETTINGS', 'Configuración'),
       ('es', 'LOG_OUT', 'Cerrar sesión'),
       ('es', 'SCAN_BARCODE', 'Escanear código de barras'),
       ('es', 'ERROR_OCCURRED', 'Ha ocurrido un error'),
       ('es', 'SNACKBAR_NEW_AUTHOR_ADDED', 'Nuevo autor agregado:'),
       ('es', 'SNACKBAR_AUTHOR_DELETED', 'El autor se ha eliminado correctamente'),
       ('es', 'BOOK', 'Libro'),
       ('es', 'SNACKBAR_NEW_CATEGORY_ADDED', 'La categoría se ha agregado correctamente'),
       ('es', 'SNACKBAR_DELETED_CATEGORY', 'La categoría se ha eliminado correctamente'),
       ('es', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'El cliente se ha agregado correctamente'),
       ('es', 'SNACKBAR_DELETED_CUSTOMER', 'El cliente se ha eliminado correctamente'),
       ('es', 'SNACKBAR_NEW_LOCATION_ADDED', 'La ubicación se ha agregado correctamente'),
       ('es', 'SNACKBAR_LOCATION_UPDATED', 'La ubicación se ha actualizado correctamente'),
       ('es', 'SNACKBAR_DELETED_LOCATION', 'La ubicación se ha eliminado correctamente'),
       ('es', 'SNACKBAR_AUTHOR_UPDATED', 'El autor se ha actualizado correctamente'),
       ('es', 'SNACKBAR_BOOK_STOCK_ADDED', 'Se ha agregado el stock del libro'),
       ('es', 'SNACKBAR_BOOK_STOCK_DELETED', 'El stock del libro se ha eliminado correctamente'),
       ('es', 'SNACKBAR_BOOK_STOCK_UPDATED', 'El stock del libro se ha actualizado correctamente'),
       ('es', 'SNACKBAR_BOOK_UPDATED', 'El libro se ha actualizado correctamente'),
       ('es', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'Se ha cambiado la imagen del libro'),
       ('es', 'SNACKBAR_BOOK_DELETED', 'El libro se ha eliminado'),
       ('es', 'BOOKED', 'Reservado'),
       ('es', 'AVAILABLE', 'Disponible'),
       ('es', 'NOT_AVAILABLE', 'No disponible'),
       ('es', 'DAMAGE', 'Daño'),
       ('es', 'SNACKBAR_CATEGORY_UPDATED', 'La categoría se ha actualizado correctamente'),
       ('es', 'SNACKBAR_PROFILE_UPDATED', 'La información del perfil se ha actualizado correctamente'),
       ('es', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'La imagen del perfil se ha eliminado correctamente'),
       ('es', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'La imagen del perfil se ha actualizado correctamente'),
       ('es', 'EDIT_AUTHOR', 'Editar autor'),
       ('es', 'ADD_AUTHOR', 'Agregar autor'),
       ('es', 'NAME', 'Nombre'),
       ('es', 'DELETE_AUTHOR_TITLE', 'Eliminar autor '),
       ('es', 'DELETE_AUTHOR_DESC', '¿Está seguro de que desea eliminar este autor?'),
       ('es', 'IMAGE_DRAG_AND_DROP', 'Arrastra y suelta una imagen'),
       ('es', 'BOOK_HOVER_INFO', '(Pase el cursor para cambiar la imagen del libro)'),
       ('es', 'EDIT_BOOK_STOCK', 'Editar stock del libro'),
       ('es', 'OVERVIEW', 'Resumen'),
       ('es', 'BOOKED_BOOKS', 'Libros reservados'),
       ('es', 'ADD_BOOK_STOCK', 'Agregar stock del libro'),
       ('es', 'BOOK_HAS_BEEN_ADDED', 'El libro "{{name}}" ha sido agregado'),
       ('es', 'ONLY_IMAGES_ALLOWED', 'Solo se permiten imágenes'),
       ('es', 'BOOK_STOCK_INFO', 'El stock del libro representa copias individuales de un libro, lo que permite controlar la cantidad y el estado. Cada stock tiene un código de barras único para su identificación. Asegúrese de agregar el código de barras al libro.'),
       ('es', 'BOOK_STOCK_STATUS', 'Estado'),
       ('es', 'BOOKED_BY', 'Reservado por'),
       ('es', 'DELETE_STOCK', 'Eliminar stock'),
       ('es', 'DELETE_STOCK_DESC', '¿Está seguro de que desea eliminar este stock del libro?'),
       ('es', 'LANGUAGE', 'Idioma'),
       ('es', 'FORMAT', 'Formato'),
       ('es', 'PAGES', 'Páginas'),
       ('es', 'PUBLISHER', 'Editorial'),
       ('es', 'PUBLISHED_DATE', 'Fecha de publicación'),
       ('es', 'DESCRIPTION', 'Descripción'),
       ('es', 'DELETE_BOOK', 'Eliminar libro '),
       ('es', 'DELETE_BOOK_DESC', '¿Está seguro de que desea eliminar este libro?'),
       ('es', 'FULLSCREEN', 'Pantalla completa'),
       ('es', 'EXIT_FULLSCREEN', 'Salir de pantalla completa'),
       ('es', 'DELETE_CATEGORY', 'Eliminar categoría '),
       ('es', 'DELETE_CATEGORY_DESC', '¿Está seguro de que desea eliminar esta categoría?'),
       ('es', 'ADD_A_BOOK', 'Agregar un libro'),
       ('es', 'REMOVE_BOOK', 'Eliminar libro'),
       ('es', 'REMOVE_BOOK_DESC', '¿Está seguro de que desea eliminar este libro de este cliente?'),
       ('es', 'EDIT_CUSTOMER', 'Editar cliente'),
       ('es', 'ADD_CUSTOMER', 'Agregar cliente'),
       ('es', 'TOTAL_BOOKS', 'Total de libros'),
       ('es', 'DELETE_CUSTOMER', 'Eliminar cliente '),
       ('es', 'DELETE_CUSTOMER_DESC', '¿Está seguro de que desea eliminar este cliente?'),
       ('es', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Libros agregados con el tiempo'),
       ('es', 'DASHBOARD_TOTAL', 'Total'),
       ('es', 'RETURN_BOOKS', 'Devolver libros'),
       ('es', 'SNACKBAR_RETURN_BOOKS', 'Los libros se han devuelto correctamente'),
       ('es', 'RETURN', 'Devolver'),
       ('es', 'DASHBOARD_CHART', 'Gráfico'),
       ('es', 'DASHBOARD_LAST_BOOKS', 'Últimos libros'),
       ('es', 'EDIT_LOCATION', 'Editar ubicación'),
       ('es', 'ADD_LOCATION', 'Agregar ubicación'),
       ('es', 'DELETE_LOCATION', 'Eliminar ubicación '),
       ('es', 'DELETE_LOCATION_DESC', '¿Está seguro de que desea eliminar esta ubicación?'),
       ('es', 'NOT_FOUND_DESC', 'No se encontró la página.'),
       ('es', 'NOT_FOUND_GO_HOME', 'Ir al inicio'),
       ('es', 'ADD_BOOK_ISBN', 'Agregar libro (ISBN)'),
       ('es', 'ADD_BOOK_ISBN_DESC', 'Agregue fácilmente un libro a su biblioteca ingresando su código ISBN. La aplicación recuperará automáticamente los detalles del libro, incluido el título, autor, descripción y más, y lo agregará a su colección.'),
       ('es', 'ISBN_CODE', 'Código ISBN'),
       ('es', 'INVALID_ISBN_CODE', 'Formato de ISBN no válido. Ingrese un ISBN-10 o ISBN-13 válido.'),
       ('es', 'DRAG_AND_DROP_BOOK_COVER', 'Arrastra y suelta la portada del libro'),
       ('es', 'USERCONF_CHANGE_PASSWORD', 'Cambiar contraseña'),
       ('es', 'USERCONF_CURRENT_PASSWORD', 'Contraseña actual'),
       ('es', 'USERCONF_NEW_PASSWORD', 'Nueva contraseña'),
       ('es', 'USERCONF_MY_PROFILE', 'Mi perfil'),
       ('es', 'USERCONF_PASSWORD_SECURITY', 'Agregue todos los caracteres necesarios para crear una contraseña segura.'),
       ('es', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'Al menos 8 caracteres'),
       ('es', 'USERCONF_PASSWORD_UPPERCASE', 'Al menos una letra mayúscula'),
       ('es', 'USERCONF_PASSWORD_ONE_NUMBER', 'Al menos un número'),
       ('es', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'Al menos un carácter especial'),
       ('es', 'USEERCONF_PASSWORD_REPEAT', 'Repita la nueva contraseña'),
       ('es', 'USERCONF_PASSWORD_NOT_MATCH', '¡Las contraseñas no coinciden!'),
       ('es', 'USERCONF_PASSWORD_CHANGED', 'Contraseña cambiada correctamente'),
       ('es', 'USERCONF_CHANGE_IMAGE', 'Cambiar imagen'),
       ('es', 'USERCONF_REMOVE_IMAGE', 'Eliminar imagen'),
       ('es', 'USERCONF_IMAGE_SUPPORT', 'Solo se admiten PNG y JPG de menos de 2 MB'),
       ('es', 'USERCONF_NAME', 'Nombre'),
       ('es', 'USERCONF_LANGUAGE_REGION', 'Idioma y región'),
       ('es', 'USERCONF_LANGUAGE', 'Idioma'),
       ('es', 'USERCONF_REGION', 'Región'),
       ('es', 'USERCONF_ACCOUNT_SECURITY', 'Seguridad de la cuenta'),
       ('es', 'USERCONF_EMAIL', 'Correo electrónico'),
       ('es', 'USERCONF_CHANGE_PASSWORD_DESC', 'Actualice la contraseña de su cuenta para mantenerla segura. Debe ingresar su contraseña actual y elegir una nueva que cumpla con los requisitos de seguridad.'),
       ('es', 'USERCONF_DELETE_DESC', 'Eliminar permanentemente la cuenta y eliminar espacio de trabajo y libros.'),
       ('es', 'USERCONF_DELETE', 'Eliminar cuenta'),
       ('es', 'USERCONF_DELETE_USER_TITLE', 'Eliminar usuario'),
       ('es', 'USERCONF_DELETE_USER_DESC', '¿Está seguro de que desea eliminar su cuenta de Paper Books? Esto eliminará permanentemente su cuenta y todo el contenido asociado.'),
       ('es', 'USERCONF_IMAGE_FORMAT_ALERT', 'Por favor, cargue una imagen PNG o JPEG.'),
       ('es', 'EDIT_CATEGORY', 'Editar categoría'),
       ('es', 'ADD_CATEGORY', 'Agregar categoría'),
       ('es', 'USERCONF_IMAGE_SIZE_ALERT', 'El tamaño del archivo debe ser inferior a 2 MB'),
       ('es', 'ADD_FILTER', 'Agregar filtro'),
       ('es', 'NO_STOCK_FILTER', 'Sin stock'),
       ('es', 'HAS_STOCK_FILTER', 'Con stock');

    INSERT INTO app_labels (language, code, text)
VALUES ('it', 'ADD_BOOK', 'Aggiungi libro'),
       ('it', 'ADD_BOOK_MANUALLY', 'Aggiungi libro manualmente'),
       ('it', 'STOCK_CODE', 'Codice stock'),
       ('it', 'CODE', 'Codice'),
       ('it', 'STOCKS', 'Stock'),
       ('it', 'CLOSE', 'Chiudi'),
       ('it', 'DELETE', 'Elimina'),
       ('it', 'CANCEL', 'Annulla'),
       ('it', 'SAVE', 'Salva'),
       ('it', 'ADD', 'Aggiungi'),
       ('it', 'UPDATE', 'Aggiorna'),
       ('it', 'ACTIONS', 'Azioni'),
       ('it', 'ADD_AND_PRINT', 'Aggiungi e stampa'),
       ('it', 'PRINT_QUEUE', 'Coda di stampa'),
       ('it', 'TOTAL_LABELS_TO_PRINT', 'Totale etichette da stampare:'),
       ('it', 'CLEAR_QUEUE', 'Svuota coda'),
       ('it', 'PRINT', 'Stampa'),
       ('it', 'SNACKBAR_PRINT_LABEL_ALREADY_ADDED', 'Etichetta già aggiunta alla coda'),
       ('it', 'SNACKBAR_PRINT_LABEL_ADDED', 'Etichetta aggiunta alla coda'),
       ('it', 'SEARCH_BOOKS', 'Cerca libri'),
       ('it', 'DASHBOARD', 'Cruscotto'),
       ('it', 'LIBRARY', 'Biblioteca'),
       ('it', 'IMAGE', 'Immagine'),
       ('it', 'LOCATIONS', 'Posizioni'),
       ('it', 'LOCATION', 'Posizione'),
       ('it', 'NO_LOCATION', '[Nessuna posizione]'),
       ('it', 'CATEGORIES', 'Categorie'),
       ('it', 'CATEGORY', 'Categoria'),
       ('it', 'CUSTOMERS', 'Clienti'),
       ('it', 'AUTHORS', 'Autori'),
       ('it', 'SETTINGS', 'Impostazioni'),
       ('it', 'LOG_OUT', 'Esci'),
       ('it', 'SCAN_BARCODE', 'Scansiona codice a barre'),
       ('it', 'ERROR_OCCURRED', 'Si è verificato un errore'),
       ('it', 'SNACKBAR_NEW_AUTHOR_ADDED', 'Nuovo autore aggiunto:'),
       ('it', 'SNACKBAR_AUTHOR_DELETED', 'autore a stato eliminato correttamente'),
       ('it', 'BOOK', 'Libro'),
       ('it', 'SNACKBAR_NEW_CATEGORY_ADDED', 'La categoria è stata aggiunta correttamente'),
       ('it', 'SNACKBAR_DELETED_CATEGORY', 'La categoria è stata eliminata correttamente'),
       ('it', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'Il cliente è stato aggiunto correttamente'),
       ('it', 'SNACKBAR_DELETED_CUSTOMER', 'Il cliente è stato eliminato correttamente'),
       ('it', 'SNACKBAR_NEW_LOCATION_ADDED', 'La posizione è stata aggiunta correttamente'),
       ('it', 'SNACKBAR_LOCATION_UPDATED', 'La posizione è stata aggiornata correttamente'),
       ('it', 'SNACKBAR_DELETED_LOCATION', 'La posizione è stata eliminata correttamente'),
       ('it', 'SNACKBAR_AUTHOR_UPDATED', 'L autore e stato aggiornato correttamente'),
       ('it', 'SNACKBAR_BOOK_STOCK_ADDED', 'Lo stock del libro è stato aggiunto'),
       ('it', 'SNACKBAR_BOOK_STOCK_DELETED', 'Lo stock del libro è stato eliminato correttamente'),
       ('it', 'SNACKBAR_BOOK_STOCK_UPDATED', 'Lo stock del libro è stato aggiornato correttamente'),
       ('it', 'SNACKBAR_BOOK_UPDATED', 'Il libro è stato aggiornato correttamente'),
       ('it', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'L immagine del libro è stata modificata'),
       ('it', 'SNACKBAR_BOOK_DELETED', 'Il libro è stato eliminato'),
       ('it', 'BOOKED', 'Prenotato'),
       ('it', 'AVAILABLE', 'Disponibile'),
       ('it', 'NOT_AVAILABLE', 'Non disponibile'),
       ('it', 'DAMAGE', 'Danno'),
       ('it', 'SNACKBAR_CATEGORY_UPDATED', 'La categoria è stata aggiornata correttamente'),
       ('it', 'SNACKBAR_PROFILE_UPDATED', 'Le informazioni del profilo sono state aggiornate correttamente'),
       ('it', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'L immagine del profilo è stata rimossa correttamente'),
       ('it', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'L immagine del profilo è stata aggiornata correttamente'),
       ('it', 'EDIT_AUTHOR', 'Modifica autore'),
       ('it', 'ADD_AUTHOR', 'Aggiungi autore'),
       ('it', 'NAME', 'Nome'),
       ('it', 'DELETE_AUTHOR_TITLE', 'Elimina autore '),
       ('it', 'DELETE_AUTHOR_DESC', 'Sei sicuro di voler rimuovere questo autore?'),
       ('it', 'IMAGE_DRAG_AND_DROP', 'Trascina e rilascia un’immagine'),
       ('it', 'BOOK_HOVER_INFO', '(Passa sopra per cambiare l’immagine del libro)'),
       ('it', 'EDIT_BOOK_STOCK', 'Modifica stock del libro'),
       ('it', 'OVERVIEW', 'Panoramica'),
       ('it', 'BOOKED_BOOKS', 'Libri prenotati'),
       ('it', 'ADD_BOOK_STOCK', 'Aggiungi stock del libro'),
       ('it', 'BOOK_HAS_BEEN_ADDED', 'Il libro "{{name}}" è stato aggiunto'),
       ('it', 'ONLY_IMAGES_ALLOWED', 'Sono consentite solo immagini'),
       ('it', 'BOOK_STOCK_INFO', 'Lo stock del libro rappresenta copie individuali di un libro, permettendo di tracciare quantità e stato. Ogni stock ha un codice a barre unico per l’identificazione. Assicurati di aggiungere il codice a barre al libro.'),
       ('it', 'BOOK_STOCK_STATUS', 'Stato'),
       ('it', 'BOOKED_BY', 'Prenotato da'),
       ('it', 'DELETE_STOCK', 'Elimina stock'),
       ('it', 'DELETE_STOCK_DESC', 'Sei sicuro di voler rimuovere questo stock del libro?'),
       ('it', 'LANGUAGE', 'Lingua'),
       ('it', 'FORMAT', 'Formato'),
       ('it', 'PAGES', 'Pagine'),
       ('it', 'PUBLISHER', 'Editore'),
       ('it', 'PUBLISHED_DATE', 'Data di pubblicazione'),
       ('it', 'DESCRIPTION', 'Descrizione'),
       ('it', 'DELETE_BOOK', 'Elimina libro '),
       ('it', 'DELETE_BOOK_DESC', 'Sei sicuro di voler eliminare questo libro?'),
       ('it', 'FULLSCREEN', 'Schermo intero'),
       ('it', 'EXIT_FULLSCREEN', 'Esci da schermo intero'),
       ('it', 'DELETE_CATEGORY', 'Elimina categoria '),
       ('it', 'DELETE_CATEGORY_DESC', 'Sei sicuro di voler rimuovere questa categoria?'),
       ('it', 'ADD_A_BOOK', 'Aggiungi un libro'),
       ('it', 'REMOVE_BOOK', 'Rimuovi libro'),
       ('it', 'REMOVE_BOOK_DESC', 'Sei sicuro di voler rimuovere questo libro da questo cliente?'),
       ('it', 'EDIT_CUSTOMER', 'Modifica cliente'),
       ('it', 'ADD_CUSTOMER', 'Aggiungi cliente'),
       ('it', 'TOTAL_BOOKS', 'Totale libri'),
       ('it', 'DELETE_CUSTOMER', 'Elimina cliente '),
       ('it', 'DELETE_CUSTOMER_DESC', 'Sei sicuro di voler rimuovere questo cliente?'),
       ('it', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Libri aggiunti nel tempo'),
       ('it', 'DASHBOARD_TOTAL', 'Totale'),
       ('it', 'SNACKBAR_RETURN_BOOKS', 'I libri sono stati restituiti con successo'),
       ('it', 'RELEASE', 'Pubblicazione'),
       ('it', 'DASHBOARD_CHART', 'Grafico'),
       ('it', 'DASHBOARD_LAST_BOOKS', 'Ultimi libri'),
       ('it', 'EDIT_LOCATION', 'Modifica posizione'),
       ('it', 'ADD_LOCATION', 'Aggiungi posizione'),
       ('it', 'DELETE_LOCATION', 'Elimina posizione '),
       ('it', 'DELETE_LOCATION_DESC', 'Sei sicuro di voler rimuovere questa posizione?'),
       ('it', 'NOT_FOUND_DESC', 'Pagina non trovata.'),
       ('it', 'NOT_FOUND_GO_HOME', 'Vai alla home'),
       ('it', 'ADD_BOOK_ISBN', 'Aggiungi libro (ISBN)'),
       ('it', 'ADD_BOOK_ISBN_DESC', 'Aggiungi facilmente un libro alla tua biblioteca inserendo il codice ISBN. L’app recupererà automaticamente i dettagli del libro, incluso titolo, autore, descrizione e altro, e lo aggiungerà alla tua collezione.'),
       ('it', 'ISBN_CODE', 'Codice ISBN'),
       ('it', 'INVALID_ISBN_CODE', 'Formato ISBN non valido. Inserisci un ISBN-10 o ISBN-13 valido.'),
       ('it', 'DRAG_AND_DROP_BOOK_COVER', 'Trascina e rilascia la copertina del libro'),
       ('it', 'USERCONF_CHANGE_PASSWORD', 'Cambia password'),
       ('it', 'USERCONF_CURRENT_PASSWORD', 'Password attuale'),
       ('it', 'USERCONF_NEW_PASSWORD', 'Nuova password'),
       ('it', 'USERCONF_MY_PROFILE', 'Il mio profilo'),
       ('it', 'USERCONF_PASSWORD_SECURITY', 'Aggiungi tutti i caratteri necessari per creare una password sicura.'),
       ('it', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'Almeno 8 caratteri'),
       ('it', 'USERCONF_PASSWORD_UPPERCASE', 'Almeno una lettera maiuscola'),
       ('it', 'USERCONF_PASSWORD_ONE_NUMBER', 'Almeno un numero'),
       ('it', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'Almeno un carattere speciale'),
       ('it', 'USEERCONF_PASSWORD_REPEAT', 'Ripeti la nuova password'),
       ('it', 'USERCONF_PASSWORD_NOT_MATCH', 'Le password non corrispondono!'),
       ('it', 'USERCONF_PASSWORD_CHANGED', 'Password modificata correttamente'),
       ('it', 'USERCONF_CHANGE_IMAGE', 'Cambia immagine'),
       ('it', 'USERCONF_REMOVE_IMAGE', 'Rimuovi immagine'),
       ('it', 'USERCONF_IMAGE_SUPPORT', 'Supportiamo solo PNG e JPG inferiori a 2 MB'),
       ('it', 'USERCONF_NAME', 'Nome'),
       ('it', 'USERCONF_LANGUAGE_REGION', 'Lingua e regione'),
       ('it', 'USERCONF_LANGUAGE', 'Lingua'),
       ('it', 'USERCONF_REGION', 'Regione'),
       ('it', 'USERCONF_ACCOUNT_SECURITY', 'Sicurezza account'),
       ('it', 'USERCONF_EMAIL', 'Email'),
       ('it', 'USERCONF_CHANGE_PASSWORD_DESC', 'Aggiorna la password del tuo account per mantenerlo sicuro. Dovrai inserire la password attuale e scegliere una nuova che soddisfi i requisiti di sicurezza.'),
       ('it', 'USERCONF_DELETE_DESC', 'Elimina permanentemente l’account e rimuovi workspace e libri.'),
       ('it', 'USERCONF_DELETE', 'Elimina account'),
       ('it', 'USERCONF_DELETE_USER_TITLE', 'Elimina utente'),
       ('it', 'USERCONF_DELETE_USER_DESC', 'Sei sicuro di voler eliminare il tuo account Paper Books? Questo rimuoverà permanentemente l’account e tutti i contenuti associati.'),
       ('it', 'USERCONF_IMAGE_FORMAT_ALERT', 'Carica un’immagine PNG o JPEG.'),
       ('it', 'EDIT_CATEGORY', 'Modifica categoria'),
       ('it', 'ADD_CATEGORY', 'Aggiungi categoria'),
       ('it', 'USERCONF_IMAGE_SIZE_ALERT', 'La dimensione del file deve essere inferiore a 2 MB'),
       ('it', 'ADD_FILTER', 'Aggiungi filtro'),
       ('it', 'NO_STOCK_FILTER', 'Senza stock'),
       ('it', 'HAS_STOCK_FILTER', 'Con stock');

-- Users table
CREATE TABLE users
(
    id              SERIAL PRIMARY KEY,
    code            VARCHAR(50) UNIQUE  NOT NULL,
    name            VARCHAR(100)        NOT NULL,
    password        VARCHAR(64)         NOT NULL,
    email           VARCHAR(100) UNIQUE NOT NULL,
    last_login_date TIMESTAMP,
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    image           BYTEA,
    language        CHAR(2)   DEFAULT 'en',
    region          CHAR(2)   DEFAULT 'US',
    disabled        BOOLEAN  DEFAULT TRUE,
    FOREIGN KEY (language) REFERENCES app_languages (code) ON DELETE SET NULL
);

-- customers table
CREATE TABLE customers
(
    id      SERIAL PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    user_id INT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Locations table
CREATE TABLE locations
(
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    user_id     INT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Categories table
CREATE TABLE categories
(
    id      SERIAL PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT unique_user_category UNIQUE (user_id, name)
);

-- Languages table
CREATE TABLE languages
(
    code CHAR(2) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO languages (code, name)
VALUES ('ar', 'Arabic'),
       ('bn', 'Bengali'),
       ('ca', 'Catalan'),
       ('de', 'German'),
       ('en', 'English'),
       ('es', 'Spanish'),
       ('fr', 'French'),
       ('hi', 'Hindi'),
       ('id', 'Indonesian'),
       ('it', 'Italian'),
       ('ja', 'Japanese'),
       ('ko', 'Korean'),
       ('mr', 'Marathi'),
       ('pt', 'Portuguese'),
       ('ru', 'Russian'),
       ('sw', 'Swahili'),
       ('ta', 'Tamil'),
       ('te', 'Telugu'),
       ('tr', 'Turkish'),
       ('ur', 'Urdu'),
       ('vi', 'Vietnamese'),
       ('zh', 'Chinese');

CREATE TABLE formats
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO formats (name)
VALUES ('Hardcover'),
       ('Paperback'),
       ('Mass Market Paperback'),
       ('Leatherbound'),
       ('Graphic Novel'),
       ('Large Print'),
       ('Library Binding'),
       ('Board Book');

-- Books table
CREATE TABLE books
(
    id             SERIAL PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    description    TEXT,
    image_url      TEXT,
    isbn           VARCHAR(20),
    category_id    INT,
    format_id      INT,
    publisher      VARCHAR(100),
    published_date DATE,
    language_code  CHAR(2),
    pages          INT,
    date_updated   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_created   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id        INT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    FOREIGN KEY (language_code) REFERENCES languages (code) ON DELETE SET NULL,
    FOREIGN KEY (format_id) REFERENCES formats (id) ON DELETE SET NULL,
    CONSTRAINT books_isbn_user_unique UNIQUE (isbn, user_id)
);

CREATE TABLE book_stocks
(
    id          SERIAL PRIMARY KEY,
    book_id     INT                                     NOT NULL,
    user_id     INT                                     NOT NULL,
    code        CHAR(10) UNIQUE                         NOT NULL,
    -- 0: available, 1: not available, 2: booked, 3: damaged
    status      SMALLINT CHECK (status IN (0, 1, 2, 3)) NOT NULL DEFAULT 0,
    location_id INT,

    -- when the book is status 2: booked, this field must be informed
    customer_id INT,

    -- Constraint: if status is 2, customer_id must be NOT NULL
    CHECK (
        (status = 2 AND customer_id IS NOT NULL) OR
        (status != 2 AND customer_id IS NULL)
        ),

    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    FOREIGN KEY (location_id) REFERENCES locations (id),
    FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE authors
(
    id      SERIAL PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    user_id INT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT unique_user_author UNIQUE (user_id, name)
);

CREATE TABLE book_authors
(
    book_id   INT NOT NULL,
    author_id INT NOT NULL,
    user_id   INT NOT NULL,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- triggers
CREATE
OR REPLACE FUNCTION enforce_customer_id_null()
RETURNS TRIGGER AS $$
BEGIN
  -- Si el nuevo status NO es 2, seteamos customer_id a NULL
  IF
NEW.status != 2 THEN
    NEW.customer_id := NULL;
END IF;

RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER trg_customer_id_null
    BEFORE UPDATE
    ON book_stocks
    FOR EACH ROW
    WHEN (OLD.status IS DISTINCT FROM NEW.status)
EXECUTE FUNCTION enforce_customer_id_null();
