-- Upgrade to v1.3.2 - schema changes made on 2026-09-26.
-- Brings an already-installed database in line with the v1.3.2 databaseSchema.sql.
-- (New installs should use databaseSchema.sql directly and skip this file.)

-- ============================================================
-- French and German UI support
-- ============================================================

INSERT INTO app_languages (code, name)
VALUES ('fr', 'French'),
       ('de', 'German');

INSERT INTO app_labels (language, code, text)
VALUES ('fr', 'ADD_BOOK', 'Ajouter un livre'),
       ('fr', 'ADD_BOOK_MANUALLY', 'Ajouter un livre manuellement'),
       ('fr', 'STOCK_CODE', 'Code de stock'),
       ('fr', 'CODE', 'Code'),
       ('fr', 'STOCKS', 'Stocks'),
       ('fr', 'CLOSE', 'Fermer'),
       ('fr', 'DELETE', 'Supprimer'),
       ('fr', 'CANCEL', 'Annuler'),
       ('fr', 'SAVE', 'Enregistrer'),
       ('fr', 'EDIT', 'Modifier'),
       ('fr', 'GENERATE_REPORT', 'Générer un rapport'),
       ('fr', 'LOAN_REPORT_TITLE', 'Rapport de prêts'),
       ('fr', 'CUSTOMER', 'Client'),
       ('fr', 'ALL_CUSTOMERS', 'Tous les clients'),
       ('fr', 'RETURNED_ON', 'Rendu le'),
       ('fr', 'STILL_ON_LOAN', 'Encore emprunté'),
       ('fr', 'NO_LOANS_FOUND', 'Aucun prêt trouvé pour les filtres sélectionnés'),
       ('fr', 'ADD', 'Ajouter'),
       ('fr', 'UPDATE', 'Mettre à jour'),
       ('fr', 'ACTIONS', 'Actions'),
       ('fr', 'ADD_AND_PRINT', 'Ajouter et imprimer'),
       ('fr', 'PRINT_QUEUE', 'File d''impression'),
       ('fr', 'TOTAL_LABELS_TO_PRINT', 'Total d''étiquettes à imprimer :'),
       ('fr', 'CLEAR_QUEUE', 'Vider la file'),
       ('fr', 'PRINT', 'Imprimer'),
       ('fr', 'SNACKBAR_PRINT_LABEL_ALREADY_ADDED', 'Étiquette déjà ajoutée à la file'),
       ('fr', 'SNACKBAR_PRINT_LABEL_ADDED', 'Étiquette ajoutée à la file'),
       ('fr', 'SEARCH_BOOKS', 'Rechercher des livres'),
       ('fr', 'DASHBOARD', 'Tableau de bord'),
       ('fr', 'LIBRARY', 'Bibliothèque'),
       ('fr', 'IMAGE', 'Image'),
       ('fr', 'LOCATIONS', 'Emplacements'),
       ('fr', 'LOCATION', 'Emplacement'),
       ('fr', 'NO_LOCATION', '[Aucun emplacement]'),
       ('fr', 'CATEGORIES', 'Catégories'),
       ('fr', 'CATEGORY', 'Catégorie'),
       ('fr', 'CUSTOMERS', 'Clients'),
       ('fr', 'AUTHORS', 'Auteurs'),
       ('fr', 'SETTINGS', 'Paramètres'),
       ('fr', 'LOG_OUT', 'Se déconnecter'),
       ('fr', 'HELP', 'Aide'),
       ('fr', 'SCAN_BARCODE', 'Scanner un code-barres'),
       ('fr', 'BARCODE_SCANNER_INSECURE_CONNECTION', 'L''accès à la caméra nécessite une connexion sécurisée (HTTPS). Demande à ton administrateur d''activer le HTTPS pour ce site.'),
       ('fr', 'BARCODE_SCANNER_CAMERA_ERROR', 'Impossible d''accéder à la caméra. Vérifie que l''autorisation d''accès à la caméra est activée pour ce site et réessaie.'),
       ('fr', 'ERROR_OCCURRED', 'Une erreur s''est produite'),
       ('fr', 'SNACKBAR_NEW_AUTHOR_ADDED', 'Nouvel auteur ajouté :'),
       ('fr', 'SNACKBAR_AUTHOR_DELETED', 'L''auteur a bien été supprimé'),
       ('fr', 'BOOK', 'Livre'),
       ('fr', 'SNACKBAR_NEW_CATEGORY_ADDED', 'La catégorie a bien été ajoutée'),
       ('fr', 'SNACKBAR_DELETED_CATEGORY', 'La catégorie a bien été supprimée'),
       ('fr', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'Le client a bien été ajouté'),
       ('fr', 'SNACKBAR_DELETED_CUSTOMER', 'Le client a bien été supprimé'),
       ('fr', 'SNACKBAR_NEW_LOCATION_ADDED', 'L''emplacement a bien été ajouté'),
       ('fr', 'SNACKBAR_LOCATION_UPDATED', 'L''emplacement a bien été mis à jour'),
       ('fr', 'SNACKBAR_DELETED_LOCATION', 'L''emplacement a bien été supprimé'),
       ('fr', 'SNACKBAR_LOCATION_SET_DEFAULT', 'Emplacement défini par défaut'),
       ('fr', 'SNACKBAR_AUTHOR_UPDATED', 'Auteur mis à jour avec succès'),
       ('fr', 'SNACKBAR_BOOK_STOCK_ADDED', 'Le stock de livre a été ajouté'),
       ('fr', 'SNACKBAR_BOOK_STOCK_DELETED', 'Stock de livre supprimé avec succès'),
       ('fr', 'SNACKBAR_BOOK_STOCK_UPDATED', 'Stock de livre mis à jour avec succès'),
       ('fr', 'SNACKBAR_BOOK_UPDATED', 'Livre mis à jour avec succès'),
       ('fr', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'L''image du livre a été modifiée'),
       ('fr', 'SNACKBAR_BOOK_DELETED', 'Le livre a été supprimé'),
       ('fr', 'SNACKBAR_BOOK_COVER_NOT_FOUND', 'Aucune couverture trouvée pour ce livre'),
       ('fr', 'BOOKED', 'Réservé'),
       ('fr', 'AVAILABLE', 'Disponible'),
       ('fr', 'NOT_AVAILABLE', 'Non disponible'),
       ('fr', 'DAMAGE', 'Endommagé'),
       ('fr', 'SNACKBAR_CATEGORY_UPDATED', 'La catégorie a été mise à jour avec succès'),
       ('fr', 'SNACKBAR_PROFILE_UPDATED', 'Les informations du profil ont été mises à jour'),
       ('fr', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'La photo de profil a été supprimée'),
       ('fr', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'La photo de profil a été mise à jour'),
       ('fr', 'EDIT_AUTHOR', 'Modifier l''auteur'),
       ('fr', 'ADD_AUTHOR', 'Ajouter un auteur'),
       ('fr', 'NAME', 'Nom'),
       ('fr', 'DELETE_AUTHOR_TITLE', 'Supprimer l''auteur '),
       ('fr', 'DELETE_AUTHOR_DESC', 'Es-tu sûr de vouloir supprimer cet auteur ?'),
       ('fr', 'IMAGE_DRAG_AND_DROP', 'Glisse-dépose une image'),
       ('fr', 'BOOK_HOVER_INFO', '(Survole pour changer l''image du livre)'),
       ('fr', 'FIND_COVER', 'Trouver une couverture'),
       ('fr', 'EDIT_BOOK_STOCK', 'Modifier le stock de livre'),
       ('fr', 'OVERVIEW', 'Aperçu'),
       ('fr', 'BOOKED_BOOKS', 'Livres réservés'),
       ('fr', 'ADD_BOOK_STOCK', 'Ajouter un stock de livre'),
       ('fr', 'BOOK_HAS_BEEN_ADDED', 'Le livre « {{name}} » a été ajouté'),
       ('fr', 'ONLY_IMAGES_ALLOWED', 'Seules les images sont autorisées'),
       ('fr', 'BOOK_STOCK_INFO', 'Le stock de livre représente les exemplaires individuels d''un livre, ce qui te permet de suivre la quantité et le statut. Chaque stock de livre possède un code-barres unique pour l''identifier. Assure-toi d''ajouter ce code-barres de stock au livre.'),
       ('fr', 'BOOK_STOCK_STATUS', 'Statut'),
       ('fr', 'BOOKED_BY', 'Réservé par'),
       ('fr', 'DELETE_STOCK', 'Supprimer le stock'),
       ('fr', 'DELETE_STOCK_DESC', 'Es-tu sûr de vouloir supprimer ce stock de livre ?'),
       ('fr', 'LANGUAGE', 'Langue'),
       ('fr', 'FORMAT', 'Format'),
       ('fr', 'PAGES', 'Pages'),
       ('fr', 'PUBLISHER', 'Éditeur'),
       ('fr', 'PUBLISHED_DATE', 'Date de publication'),
       ('fr', 'DESCRIPTION', 'Description'),
       ('fr', 'DELETE_BOOK', 'Supprimer le livre '),
       ('fr', 'DELETE_BOOK_DESC', 'Es-tu sûr de vouloir supprimer ce livre ?'),
       ('fr', 'EBOOK_FILE', 'Fichiers ebook'),
       ('fr', 'EBOOK_FILE_DRAG_AND_DROP', 'Glisse-dépose un fichier epub, pdf ou Kindle'),
       ('fr', 'EBOOK_FILE_HOVER_INFO', '(Copie de secours en cas de perte de ta liseuse)'),
       ('fr', 'ONLY_EBOOK_FILES_ALLOWED', 'Seuls les fichiers EPUB, PDF ou Kindle sont autorisés'),
       ('fr', 'PREVIEW_UNAVAILABLE', 'Aperçu indisponible'),
       ('fr', 'FILE_TOO_LARGE', 'Le fichier est trop volumineux (100 Mo max)'),
       ('fr', 'DOWNLOAD', 'Télécharger'),
       ('fr', 'FULLSCREEN', 'Plein écran'),
       ('fr', 'EXIT_FULLSCREEN', 'Quitter le plein écran'),
       ('fr', 'SNACKBAR_BOOK_FILE_UPLOADED', 'Fichier ebook envoyé'),
       ('fr', 'SNACKBAR_BOOK_FILE_DELETED', 'Fichier ebook supprimé'),
       ('fr', 'DELETE_FILE', 'Supprimer le fichier '),
       ('fr', 'DELETE_FILE_DESC', 'Es-tu sûr de vouloir supprimer ce fichier ebook ?'),
       ('fr', 'DELETE_CATEGORY', 'Supprimer la catégorie '),
       ('fr', 'DELETE_CATEGORY_DESC', 'Es-tu sûr de vouloir supprimer cette catégorie ?'),
       ('fr', 'ADD_A_BOOK', 'Ajouter un livre'),
       ('fr', 'REMOVE_BOOK', 'Retirer le livre'),
       ('fr', 'REMOVE_BOOK_DESC', 'Es-tu sûr de vouloir retirer ce livre de ce client ?'),
       ('fr', 'EDIT_CUSTOMER', 'Modifier le client'),
       ('fr', 'ADD_CUSTOMER', 'Ajouter un client'),
       ('fr', 'TOTAL_BOOKS', 'Total de livres'),
       ('fr', 'DELETE_CUSTOMER', 'Supprimer le client '),
       ('fr', 'DELETE_CUSTOMER_DESC', 'Es-tu sûr de vouloir supprimer ce client ?'),
       ('fr', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Livres ajoutés dans le temps'),
       ('fr', 'DASHBOARD_TOTAL', 'Total'),
       ('fr', 'RETURN_BOOKS', 'Rendre des livres'),
       ('fr', 'SNACKBAR_RETURN_BOOKS', 'Les livres ont bien été rendus'),
       ('fr', 'RETURN', 'Rendre'),
       ('fr', 'DASHBOARD_CHART', 'Graphique'),
       ('fr', 'DASHBOARD_LAST_BOOKS', 'Derniers livres'),
       ('fr', 'DASHBOARD_HERO_PREFIX', 'Tu as'),
       ('fr', 'DASHBOARD_HERO_SUFFIX', 'nouveaux livres ce mois-ci'),
       ('fr', 'DASHBOARD_ALL_CATEGORIES', 'Toutes'),
       ('fr', 'DASHBOARD_BROWSE_CATEGORIES', 'Parcourir par catégorie'),
       ('fr', 'DASHBOARD_ON_LOAN', 'Actuellement emprunté'),
       ('fr', 'DASHBOARD_LOANED_TO', 'Emprunté par'),
       ('fr', 'DASHBOARD_NO_LOANS', 'Rien d''emprunté pour le moment'),
       ('fr', 'LOANS', 'Prêts'),
       ('fr', 'LOANED_ON', 'Emprunté le'),
       ('fr', 'DATE_FROM', 'Du'),
       ('fr', 'DATE_TO', 'Au'),
       ('fr', 'ALL_GROUPS', 'Tous les groupes'),
       ('fr', 'EMPTY_LOANS_TITLE', 'Aucun livre emprunté'),
       ('fr', 'EMPTY_LOANS_DESC', 'Les livres actuellement empruntés par un client apparaîtront ici.'),
       ('fr', 'VIEW_ALL', 'Tout voir'),
       ('fr', 'DASHBOARD_LOANS_NOTE', 'Affichage des 5 prêts les plus récents'),
       ('fr', 'EDIT_LOCATION', 'Modifier l''emplacement'),
       ('fr', 'ADD_LOCATION', 'Ajouter un emplacement'),
       ('fr', 'DELETE_LOCATION', 'Supprimer l''emplacement '),
       ('fr', 'DELETE_LOCATION_DESC', 'Es-tu sûr de vouloir supprimer cet emplacement ?'),
       ('fr', 'DEFAULT', 'Par défaut'),
       ('fr', 'SET_AS_DEFAULT_LOCATION', 'Définir comme emplacement par défaut'),
       ('fr', 'NOT_FOUND_DESC', 'La page est introuvable.'),
       ('fr', 'NOT_FOUND_GO_HOME', 'Retourner à l''accueil'),
       ('fr', 'ADD_BOOK_ISBN', 'Ajouter un livre (ISBN)'),
       ('fr', 'ADD_BOOK_ISBN_DESC', 'Ajoute facilement un livre à ta bibliothèque en saisissant son code ISBN. L''application récupère automatiquement les détails du livre — titre, auteur, description et plus encore — et l''ajoute directement à ta collection.'),
       ('fr', 'ISBN_CODE', 'Code ISBN'),
       ('fr', 'INVALID_ISBN_CODE', 'Format ISBN invalide. Merci de saisir un ISBN-10 ou ISBN-13 valide.'),
       ('fr', 'ISBN_BOOK_NOT_FOUND', 'Livre introuvable'),
       ('fr', 'ISBN_ADD_ERROR', 'Erreur lors de l''ajout du livre'),
       ('fr', 'DRAG_AND_DROP_BOOK_COVER', 'Glisse-dépose la couverture du livre'),
       ('fr', 'USERCONF_CHANGE_PASSWORD', 'Changer le mot de passe'),
       ('fr', 'USERCONF_CURRENT_PASSWORD', 'Mot de passe actuel'),
       ('fr', 'USERCONF_NEW_PASSWORD', 'Nouveau mot de passe'),
       ('fr', 'USERCONF_MY_PROFILE', 'Mon profil'),
       ('fr', 'USERCONF_PASSWORD_SECURITY', 'Ajoute tous les caractères nécessaires pour créer un mot de passe sécurisé.'),
       ('fr', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'Au moins 8 caractères'),
       ('fr', 'USERCONF_PASSWORD_UPPERCASE', 'Au moins une majuscule'),
       ('fr', 'USERCONF_PASSWORD_ONE_NUMBER', 'Au moins un chiffre'),
       ('fr', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'Au moins un caractère spécial'),
       ('fr', 'USEERCONF_PASSWORD_REPEAT', 'Répète le nouveau mot de passe'),
       ('fr', 'USERCONF_PASSWORD_NOT_MATCH', 'Les mots de passe ne correspondent pas !'),
       ('fr', 'USERCONF_PASSWORD_CHANGED', 'Mot de passe modifié avec succès'),
       ('fr', 'USERCONF_CHANGE_IMAGE', 'Changer l''image'),
       ('fr', 'USERCONF_REMOVE_IMAGE', 'Supprimer l''image'),
       ('fr', 'USERCONF_IMAGE_SUPPORT', 'Seuls les PNG et JPG de moins de 2 Mo sont pris en charge'),
       ('fr', 'USERCONF_NAME', 'Nom'),
       ('fr', 'USERCONF_LANGUAGE_REGION', 'Langue et région'),
       ('fr', 'USERCONF_LANGUAGE', 'Langue'),
       ('fr', 'USERCONF_REGION', 'Région'),
       ('fr', 'USERCONF_ACCOUNT_SECURITY', 'Sécurité du compte'),
       ('fr', 'USERCONF_EMAIL', 'E-mail'),
       ('fr', 'USERCONF_EMAIL_DESC', 'Utilisé pour te connecter et pour les notifications de compte.'),
       ('fr', 'USERCONF_CHANGE_PASSWORD_DESC', 'Mets à jour le mot de passe de ton compte pour le garder sécurisé. Tu devras saisir ton mot de passe actuel et en choisir un nouveau qui respecte les critères de sécurité.'),
       ('fr', 'USERCONF_DELETE_DESC', 'Supprime définitivement le compte ainsi que l''espace de travail et les livres.'),
       ('fr', 'USERCONF_DELETE', 'Supprimer le compte'),
       ('fr', 'USERCONF_DELETE_USER_TITLE', 'Supprimer l''utilisateur'),
       ('fr', 'USERCONF_DELETE_USER_DESC', 'Es-tu sûr de vouloir supprimer ton compte Vaultisse ? Cela supprimera définitivement ton compte et tout le contenu associé.'),
       ('fr', 'USERCONF_APPEARANCE', 'Apparence'),
       ('fr', 'USERCONF_THEME_BEIGE', 'Salle de lecture'),
       ('fr', 'USERCONF_THEME_BEIGE_DESC', 'Chaleureux, clair, aux tons papier.'),
       ('fr', 'USERCONF_THEME_LIBRARY', 'Rayonnage ouvert'),
       ('fr', 'USERCONF_THEME_LIBRARY_DESC', 'Sombre, aux tons froids, agréable pour les yeux le soir.'),
       ('fr', 'USERCONF_COMPACT_MENU', 'Menu compact'),
       ('fr', 'USERCONF_COMPACT_MENU_DESC', 'Réduit la barre latérale à de simples icônes, qui se déplie quand tu la survoles.'),
       ('fr', 'SNACKBAR_APPEARANCE_UPDATED', 'Apparence mise à jour'),
       ('fr', 'USERCONF_FEATURES', 'Fonctionnalités'),
       ('fr', 'USERCONF_LEASING', 'Prêts'),
       ('fr', 'USERCONF_LEASING_DESC', 'Suis qui emprunte quoi. Active les pages Prêts et Clients dans la barre latérale.'),
       ('fr', 'SNACKBAR_LEASING_UPDATED', 'Préférence de prêt mise à jour'),
       ('fr', 'USERCONF_SESSIONS', 'Sessions actives'),
       ('fr', 'USERCONF_SESSIONS_DESC', 'Appareils actuellement connectés à ton compte.'),
       ('fr', 'USERCONF_SESSIONS_EMPTY', 'Aucune session active'),
       ('fr', 'USERCONF_SESSION_CURRENT', 'Cet appareil'),
       ('fr', 'USERCONF_SESSION_LOG_OUT', 'Se déconnecter'),
       ('fr', 'USERCONF_SESSION_LAST_ACTIVE', 'Dernière activité'),
       ('fr', 'USERCONF_SESSION_LOGOUT_TITLE', 'Déconnecter cet appareil ?'),
       ('fr', 'USERCONF_SESSION_LOGOUT_DESC', 'Cet appareil sera déconnecté immédiatement.'),
       ('fr', 'SNACKBAR_SESSION_REVOKED', 'Appareil déconnecté'),
       ('fr', 'USERCONF_LOGIN_ACTIVITY', 'Connexions récentes'),
       ('fr', 'USERCONF_LOGIN_ACTIVITY_DESC', 'Les dernières connexions à ton compte.'),
       ('fr', 'USERCONF_LOGIN_ACTIVITY_EMPTY', 'Aucune activité de connexion pour le moment'),
       ('fr', 'ACTIVITY_LOGIN', 'Connecté'),
       ('fr', 'ACTIVITY_LOGIN_FAILED', 'Tentative de connexion échouée'),
       ('fr', 'ACTIVITY_LOGOUT', 'Déconnecté'),
       ('fr', 'ACTIVITY_PASSWORD_CHANGED', 'Mot de passe modifié'),
       ('fr', 'DEVICE_UNKNOWN', 'Appareil inconnu'),
       ('fr', 'TWOFA_TITLE', 'Authentification à deux facteurs'),
       ('fr', 'TWOFA_DESC', 'Exige un code provenant d''une application d''authentification lors de la connexion.'),
       ('fr', 'TWOFA_STATUS_ENABLED', 'Activée'),
       ('fr', 'TWOFA_STATUS_DISABLED', 'Désactivée'),
       ('fr', 'TWOFA_ENABLE', 'Activer'),
       ('fr', 'TWOFA_DISABLE', 'Désactiver'),
       ('fr', 'TWOFA_SETUP_TITLE', 'Configurer l''authentification à deux facteurs'),
       ('fr', 'TWOFA_SETUP_SCAN_DESC', 'Scanne ce QR code avec une application d''authentification (Google Authenticator, Authy, 1Password, ...), puis saisis le code à 6 chiffres qui s''affiche.'),
       ('fr', 'TWOFA_SETUP_MANUAL_KEY', 'Ou saisis cette clé manuellement :'),
       ('fr', 'TWOFA_CODE', 'Code de vérification'),
       ('fr', 'TWOFA_INVALID_CODE', 'Code invalide. Merci de réessayer.'),
       ('fr', 'TWOFA_BACKUP_CODES_TITLE', 'Enregistre tes codes de secours'),
       ('fr', 'TWOFA_BACKUP_CODES_DESC', 'Chaque code peut être utilisé une fois pour te connecter si tu perds l''accès à ton application d''authentification. Conserve-les en lieu sûr - ils ne seront plus jamais affichés.'),
       ('fr', 'TWOFA_SAVED_CODES_CONFIRM', 'J''ai enregistré ces codes'),
       ('fr', 'TWOFA_DISABLE_TITLE', 'Désactiver l''authentification à deux facteurs'),
       ('fr', 'TWOFA_DISABLE_DESC', 'Saisis ton mot de passe pour désactiver l''authentification à deux facteurs. Tes codes de secours ne fonctionneront plus.'),
       ('fr', 'TWOFA_DISABLE_PASSWORD', 'Mot de passe'),
       ('fr', 'TWOFA_ENABLED_SNACKBAR', 'Authentification à deux facteurs activée'),
       ('fr', 'TWOFA_DISABLED_SNACKBAR', 'Authentification à deux facteurs désactivée'),
       ('fr', 'USERCONF_IMAGE_FORMAT_ALERT', 'Merci d''envoyer une image au format PNG ou JPEG.'),
       ('fr', 'EDIT_CATEGORY', 'Modifier la catégorie'),
       ('fr', 'ADD_CATEGORY', 'Ajouter une catégorie'),
       ('fr', 'USERCONF_IMAGE_SIZE_ALERT', 'La taille du fichier doit être inférieure à 2 Mo'),
       ('fr', 'ADD_FILTER', 'Ajouter un filtre'),
       ('fr', 'NO_STOCK_FILTER', 'Aucun stock'),
       ('fr', 'HAS_STOCK_FILTER', 'Avec stock'),
       ('fr', 'ON_LOAN_FILTER', 'Emprunté'),
       ('fr', 'RECENT_FILTER', 'Récent'),
       ('fr', 'UPLOAD_DATE_FILTER', 'Date d''ajout'),
       ('fr', 'CATEGORY_FILTER', 'Catégorie'),
       ('fr', 'ALL_CATEGORIES', 'Toutes les catégories'),
       ('fr', 'GROUP_BY_CATEGORY', 'Grouper par catégorie'),
       ('fr', 'UNCATEGORIZED', 'Sans catégorie'),
       ('fr', 'WANT_TO_READ', 'À lire'),
       ('fr', 'CURRENTLY_READING', 'En cours de lecture'),
       ('fr', 'READ', 'Lu'),
       ('fr', 'READING_STATUS', 'Statut de lecture'),
       ('fr', 'DASHBOARD_TOTAL_READ', 'Livres lus'),
       ('fr', 'DASHBOARD_NO_WANT_TO_READ', 'Ta liste « à lire » est vide'),
       ('fr', 'DASHBOARD_NO_CURRENTLY_READING', 'Tu ne lis rien en ce moment'),
       ('fr', 'SORT_BY', 'Trier par'),
       ('fr', 'SORT_NAME_ASC', 'Nom (A-Z)'),
       ('fr', 'SORT_NAME_DESC', 'Nom (Z-A)'),
       ('fr', 'SORT_DATE_NEWEST', 'Plus récent d''abord'),
       ('fr', 'SORT_DATE_OLDEST', 'Plus ancien d''abord'),
       ('fr', 'APPLY', 'Appliquer'),
       ('fr', 'CLEAR', 'Effacer'),
       ('fr', 'GROUPS', 'Groupes'),
       ('fr', 'GROUP', 'Groupe'),
       ('fr', 'NO_GROUP', 'Aucun groupe'),
       ('fr', 'NO_MEMBERS', 'Aucun membre'),
       ('fr', 'MANAGE_GROUPS', 'Gérer les groupes'),
       ('fr', 'ADD_GROUP', 'Ajouter un groupe'),
       ('fr', 'EDIT_GROUP', 'Modifier le groupe'),
       ('fr', 'DELETE_GROUP', 'Supprimer le groupe'),
       ('fr', 'DELETE_GROUP_DESC', 'Es-tu sûr de vouloir supprimer ce groupe ? Les clients de ce groupe ne seront pas supprimés.'),
       ('fr', 'GROUP_MEMBERS', 'Membres du groupe'),
       ('fr', 'ADD_MEMBERS_TO_GROUP', 'Ajouter des membres'),
       ('fr', 'TOTAL_CUSTOMERS', 'Clients'),
       ('fr', 'SNACKBAR_NEW_GROUP_ADDED', 'Groupe ajouté'),
       ('fr', 'SNACKBAR_GROUP_UPDATED', 'Groupe mis à jour'),
       ('fr', 'SNACKBAR_DELETED_GROUP', 'Groupe supprimé'),
       ('fr', 'MOVE_TO_GROUP', 'Déplacer vers un groupe'),
       ('fr', 'MOVE', 'Déplacer'),
       ('fr', 'SELECTED', 'sélectionné(s)'),
       ('fr', 'GROUPS_DRAG_DROP_HINT', 'Glisse-dépose les clients entre les groupes, ou sélectionnes-en plusieurs pour les déplacer en une fois.'),
       ('fr', 'EMPTY_LIBRARY_TITLE', 'Ajoute ton premier livre'),
       ('fr', 'EMPTY_LIBRARY_DESC', 'Scanne un ISBN ou ajoute un livre manuellement pour commencer à construire ta bibliothèque.'),
       ('fr', 'EMPTY_LOCATIONS_TITLE', 'Ajoute ton premier emplacement'),
       ('fr', 'EMPTY_LOCATIONS_DESC', 'Crée des étagères, des pièces ou des annexes pour organiser où vivent tes livres.'),
       ('fr', 'EMPTY_CUSTOMERS_TITLE', 'Ajoute ton premier client'),
       ('fr', 'EMPTY_CUSTOMERS_DESC', 'Ajoute des clients pour commencer à prêter et suivre tes livres.'),
       ('fr', 'EMPTY_CATEGORIES_TITLE', 'Ajoute ta première catégorie'),
       ('fr', 'EMPTY_CATEGORIES_DESC', 'Crée des catégories pour organiser et classer tes livres.'),
       ('fr', 'EMPTY_AUTHORS_TITLE', 'Ajoute ton premier auteur'),
       ('fr', 'EMPTY_AUTHORS_DESC', 'Ajoute des auteurs pour les relier aux livres de ta bibliothèque.'),
       ('fr', 'EMPTY_LAST_BOOKS_TITLE', 'Pas encore de livre'),
       ('fr', 'EMPTY_LAST_BOOKS_DESC', 'Les livres que tu ajoutes apparaîtront ici.'),
       ('fr', 'PUBLIC_INSTITUTION_SENSITIVE_DATA_WARNING', 'Ce compte est enregistré en tant qu''institution publique. Évite de saisir des informations personnelles sensibles ici — utilise plutôt des codes ou identifiants étudiants que toi seul peux identifier, à la place des noms complets.'),
       ('fr', 'IMPORT', 'Importer'),
       ('fr', 'IMPORT_LIBRARY_DESC', 'Ajoute en masse des livres à ta bibliothèque à partir d''un fichier CSV. Choisis la provenance du fichier, puis envoie-le — chaque ligne devient un nouveau livre, et tout livre que tu possèdes déjà (identifié par l''ISBN, ou par le titre en l''absence d''ISBN) est automatiquement ignoré.'),
       ('fr', 'IMPORT_SELECT_ORIGIN', 'Importer depuis'),
       ('fr', 'IMPORT_ORIGIN_VAULTISSE', 'Vaultisse'),
       ('fr', 'IMPORT_ORIGIN_VAULTISSE_DESC', 'Un CSV suivant le modèle propre à Vaultisse'),
       ('fr', 'IMPORT_ORIGIN_GOODREADS', 'Goodreads'),
       ('fr', 'IMPORT_ORIGIN_GOODREADS_DESC', 'Ta bibliothèque exportée depuis Goodreads'),
       ('fr', 'IMPORT_DROPZONE_TITLE', 'Clique ou glisse-dépose un fichier CSV'),
       ('fr', 'IMPORT_MAX_SIZE', 'Taille maximale du fichier : {maxSizeMb} Mo'),
       ('fr', 'IMPORT_FILE_TOO_LARGE', 'Ce fichier est trop volumineux — la taille maximale autorisée est de {maxSizeMb} Mo'),
       ('fr', 'IMPORT_ONLY_CSV_ALLOWED', 'Seuls les fichiers CSV sont autorisés'),
       ('fr', 'IMPORT_DOWNLOAD_TEMPLATE', 'Télécharger le modèle'),
       ('fr', 'SNACKBAR_IMPORT_SUCCESS', 'Total de livres importés : {count}'),
       ('fr', 'REMOVE', 'Retirer'),
       ('fr', 'VAULTS', 'Bibliothèques'),
       ('fr', 'VAULTS_DESC', 'Une bibliothèque peut être partagée avec d''autres personnes. Passe d''une bibliothèque à l''autre parmi celles auxquelles tu appartiens, invite d''autres personnes dans la tienne et gère les rôles des membres.'),
       ('fr', 'VAULTS_EMPTY', 'Tu n''appartiens encore à aucune bibliothèque'),
       ('fr', 'VAULT_ACTIVE', 'Active'),
       ('fr', 'VAULT_SWITCH', 'Changer'),
       ('fr', 'VAULT_MANAGE', 'Gérer'),
       ('fr', 'ADD_VAULT', 'Nouvelle bibliothèque'),
       ('fr', 'VAULT_SETTINGS', 'Paramètres'),
       ('fr', 'VAULT_INVITE', 'Lien d''invitation'),
       ('fr', 'VAULT_INVITE_DESC', 'Toute personne disposant de ce lien peut demander à rejoindre cette bibliothèque. Tu devras l''approuver avant qu''elle puisse voir ou ajouter quoi que ce soit.'),
       ('fr', 'VAULT_MEMBERS', 'Membres'),
       ('fr', 'VAULT_YOU', 'Toi'),
       ('fr', 'VAULT_STATUS_PENDING', 'En attente'),
       ('fr', 'VAULT_STATUS_REJECTED', 'Rejeté'),
       ('fr', 'VAULT_LEAVE', 'Quitter'),
       ('fr', 'VAULT_LEAVE_DESC', 'Es-tu sûr de vouloir quitter cette bibliothèque ? Tu perdras l''accès à ses livres et à ses données à moins d''être réinvité.'),
       ('fr', 'VAULT_REMOVE_MEMBER', 'Retirer le membre'),
       ('fr', 'VAULT_REMOVE_MEMBER_DESC', 'Es-tu sûr de vouloir retirer {name} de cette bibliothèque ?'),
       ('fr', 'DELETE_VAULT', 'Supprimer la bibliothèque'),
       ('fr', 'DELETE_VAULT_DESC', 'Es-tu sûr de vouloir supprimer cette bibliothèque ? Cette action est irréversible. Si elle contient encore des livres, des clients ou d''autre contenu, il te sera demandé de tout déplacer vers une autre bibliothèque au préalable.'),
       ('fr', 'VAULT_JOIN_REQUEST', 'Demander à rejoindre'),
       ('fr', 'VAULT_JOIN_REQUESTED', 'Demande envoyée. Un membre disposant des droits de gestion des membres doit l''approuver avant que tu puisses accéder à cette bibliothèque.'),
       ('fr', 'VAULT_JOIN_INVALID', 'Ce lien d''invitation est invalide ou a expiré.'),
       ('fr', 'SNACKBAR_VAULT_CREATED', 'Bibliothèque créée avec succès'),
       ('fr', 'SNACKBAR_VAULT_UPDATED', 'Bibliothèque mise à jour avec succès'),
       ('fr', 'SNACKBAR_VAULT_DELETED', 'Bibliothèque supprimée avec succès'),
       ('fr', 'SNACKBAR_VAULT_SWITCHED', 'Bibliothèque active changée'),
       ('fr', 'SNACKBAR_VAULT_LEFT', 'Tu as quitté la bibliothèque'),
       ('fr', 'SNACKBAR_MEMBER_UPDATED', 'Membre mis à jour avec succès'),
       ('fr', 'SNACKBAR_MEMBER_REMOVED', 'Membre retiré avec succès'),
       ('fr', 'SNACKBAR_INVITE_LINK_COPIED', 'Lien d''invitation copié dans le presse-papiers'),
       ('fr', 'BOOK_ADDED_BY', 'Ajouté par'),
       ('fr', 'VAULT_DELETE_ONLY_VAULT', 'C''est la seule bibliothèque à laquelle tu appartiens - tu ne peux pas la supprimer'),
       ('fr', 'VAULT_TRANSFER_TITLE', 'Déplace d''abord son contenu'),
       ('fr', 'VAULT_TRANSFER_DESC', 'Cette bibliothèque contient encore des livres, des clients ou d''autre contenu. Choisis une autre bibliothèque où tout déplacer avant de la supprimer.'),
       ('fr', 'VAULT_TRANSFER_TARGET', 'Déplacer vers'),
       ('fr', 'VAULT_TRANSFER_CONFIRM', 'Déplacer et supprimer');

INSERT INTO app_labels (language, code, text)
VALUES ('de', 'ADD_BOOK', 'Buch hinzufügen'),
       ('de', 'ADD_BOOK_MANUALLY', 'Buch manuell hinzufügen'),
       ('de', 'STOCK_CODE', 'Bestandscode'),
       ('de', 'CODE', 'Code'),
       ('de', 'STOCKS', 'Bestände'),
       ('de', 'CLOSE', 'Schließen'),
       ('de', 'DELETE', 'Löschen'),
       ('de', 'CANCEL', 'Abbrechen'),
       ('de', 'SAVE', 'Speichern'),
       ('de', 'EDIT', 'Bearbeiten'),
       ('de', 'GENERATE_REPORT', 'Bericht erstellen'),
       ('de', 'LOAN_REPORT_TITLE', 'Ausleihbericht'),
       ('de', 'CUSTOMER', 'Kunde'),
       ('de', 'ALL_CUSTOMERS', 'Alle Kunden'),
       ('de', 'RETURNED_ON', 'Zurückgegeben am'),
       ('de', 'STILL_ON_LOAN', 'Noch ausgeliehen'),
       ('de', 'NO_LOANS_FOUND', 'Keine Ausleihen für die gewählten Filter gefunden'),
       ('de', 'ADD', 'Hinzufügen'),
       ('de', 'UPDATE', 'Aktualisieren'),
       ('de', 'ACTIONS', 'Aktionen'),
       ('de', 'ADD_AND_PRINT', 'Hinzufügen und drucken'),
       ('de', 'PRINT_QUEUE', 'Druckwarteschlange'),
       ('de', 'TOTAL_LABELS_TO_PRINT', 'Anzahl zu druckender Etiketten:'),
       ('de', 'CLEAR_QUEUE', 'Warteschlange leeren'),
       ('de', 'PRINT', 'Drucken'),
       ('de', 'SNACKBAR_PRINT_LABEL_ALREADY_ADDED', 'Etikett wurde bereits zur Warteschlange hinzugefügt'),
       ('de', 'SNACKBAR_PRINT_LABEL_ADDED', 'Etikett zur Warteschlange hinzugefügt'),
       ('de', 'SEARCH_BOOKS', 'Bücher suchen'),
       ('de', 'DASHBOARD', 'Übersicht'),
       ('de', 'LIBRARY', 'Bibliothek'),
       ('de', 'IMAGE', 'Bild'),
       ('de', 'LOCATIONS', 'Standorte'),
       ('de', 'LOCATION', 'Standort'),
       ('de', 'NO_LOCATION', '[Kein Standort]'),
       ('de', 'CATEGORIES', 'Kategorien'),
       ('de', 'CATEGORY', 'Kategorie'),
       ('de', 'CUSTOMERS', 'Kunden'),
       ('de', 'AUTHORS', 'Autoren'),
       ('de', 'SETTINGS', 'Einstellungen'),
       ('de', 'LOG_OUT', 'Abmelden'),
       ('de', 'HELP', 'Hilfe'),
       ('de', 'SCAN_BARCODE', 'Barcode scannen'),
       ('de', 'BARCODE_SCANNER_INSECURE_CONNECTION', 'Für den Kamerazugriff ist eine sichere Verbindung (HTTPS) erforderlich. Bitte deinen Administrator, HTTPS für diese Seite zu aktivieren.'),
       ('de', 'BARCODE_SCANNER_CAMERA_ERROR', 'Zugriff auf die Kamera nicht möglich. Überprüfe, ob die Kameraberechtigung für diese Seite erlaubt ist, und versuche es erneut.'),
       ('de', 'ERROR_OCCURRED', 'Ein Fehler ist aufgetreten'),
       ('de', 'SNACKBAR_NEW_AUTHOR_ADDED', 'Neuer Autor hinzugefügt:'),
       ('de', 'SNACKBAR_AUTHOR_DELETED', 'Der Autor wurde erfolgreich gelöscht'),
       ('de', 'BOOK', 'Buch'),
       ('de', 'SNACKBAR_NEW_CATEGORY_ADDED', 'Die Kategorie wurde erfolgreich hinzugefügt'),
       ('de', 'SNACKBAR_DELETED_CATEGORY', 'Die Kategorie wurde erfolgreich gelöscht'),
       ('de', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'Der Kunde wurde erfolgreich hinzugefügt'),
       ('de', 'SNACKBAR_DELETED_CUSTOMER', 'Der Kunde wurde erfolgreich gelöscht'),
       ('de', 'SNACKBAR_NEW_LOCATION_ADDED', 'Der Standort wurde erfolgreich hinzugefügt'),
       ('de', 'SNACKBAR_LOCATION_UPDATED', 'Der Standort wurde erfolgreich aktualisiert'),
       ('de', 'SNACKBAR_DELETED_LOCATION', 'Der Standort wurde erfolgreich gelöscht'),
       ('de', 'SNACKBAR_LOCATION_SET_DEFAULT', 'Standort als Standard festgelegt'),
       ('de', 'SNACKBAR_AUTHOR_UPDATED', 'Autor erfolgreich aktualisiert'),
       ('de', 'SNACKBAR_BOOK_STOCK_ADDED', 'Der Buchbestand wurde hinzugefügt'),
       ('de', 'SNACKBAR_BOOK_STOCK_DELETED', 'Buchbestand erfolgreich gelöscht'),
       ('de', 'SNACKBAR_BOOK_STOCK_UPDATED', 'Buchbestand erfolgreich aktualisiert'),
       ('de', 'SNACKBAR_BOOK_UPDATED', 'Buch erfolgreich aktualisiert'),
       ('de', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'Das Buchbild wurde geändert'),
       ('de', 'SNACKBAR_BOOK_DELETED', 'Das Buch wurde gelöscht'),
       ('de', 'SNACKBAR_BOOK_COVER_NOT_FOUND', 'Kein Cover für dieses Buch gefunden'),
       ('de', 'BOOKED', 'Reserviert'),
       ('de', 'AVAILABLE', 'Verfügbar'),
       ('de', 'NOT_AVAILABLE', 'Nicht verfügbar'),
       ('de', 'DAMAGE', 'Beschädigt'),
       ('de', 'SNACKBAR_CATEGORY_UPDATED', 'Die Kategorie wurde erfolgreich aktualisiert'),
       ('de', 'SNACKBAR_PROFILE_UPDATED', 'Profilinformationen erfolgreich aktualisiert'),
       ('de', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'Das Profilbild wurde erfolgreich entfernt'),
       ('de', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'Das Profilbild wurde erfolgreich aktualisiert'),
       ('de', 'EDIT_AUTHOR', 'Autor bearbeiten'),
       ('de', 'ADD_AUTHOR', 'Autor hinzufügen'),
       ('de', 'NAME', 'Name'),
       ('de', 'DELETE_AUTHOR_TITLE', 'Autor löschen '),
       ('de', 'DELETE_AUTHOR_DESC', 'Möchtest du diesen Autor wirklich entfernen?'),
       ('de', 'IMAGE_DRAG_AND_DROP', 'Bild per Drag & Drop ablegen'),
       ('de', 'BOOK_HOVER_INFO', '(Zum Ändern des Buchbilds darüberfahren)'),
       ('de', 'FIND_COVER', 'Cover suchen'),
       ('de', 'EDIT_BOOK_STOCK', 'Buchbestand bearbeiten'),
       ('de', 'OVERVIEW', 'Übersicht'),
       ('de', 'BOOKED_BOOKS', 'Reservierte Bücher'),
       ('de', 'ADD_BOOK_STOCK', 'Buchbestand hinzufügen'),
       ('de', 'BOOK_HAS_BEEN_ADDED', 'Das Buch „{{name}}“ wurde hinzugefügt'),
       ('de', 'ONLY_IMAGES_ALLOWED', 'Nur Bilder sind erlaubt'),
       ('de', 'BOOK_STOCK_INFO', 'Der Buchbestand steht für die einzelnen Exemplare eines Buchs und ermöglicht es dir, Menge und Status zu verfolgen. Jeder Buchbestand hat einen eindeutigen Barcode zur Identifizierung. Achte darauf, den Bestands-Barcode dem Buch hinzuzufügen.'),
       ('de', 'BOOK_STOCK_STATUS', 'Status'),
       ('de', 'BOOKED_BY', 'Reserviert von'),
       ('de', 'DELETE_STOCK', 'Bestand löschen'),
       ('de', 'DELETE_STOCK_DESC', 'Möchtest du diesen Buchbestand wirklich entfernen?'),
       ('de', 'LANGUAGE', 'Sprache'),
       ('de', 'FORMAT', 'Format'),
       ('de', 'PAGES', 'Seiten'),
       ('de', 'PUBLISHER', 'Verlag'),
       ('de', 'PUBLISHED_DATE', 'Erscheinungsdatum'),
       ('de', 'DESCRIPTION', 'Beschreibung'),
       ('de', 'DELETE_BOOK', 'Buch löschen '),
       ('de', 'DELETE_BOOK_DESC', 'Möchtest du dieses Buch wirklich löschen?'),
       ('de', 'EBOOK_FILE', 'E-Book-Dateien'),
       ('de', 'EBOOK_FILE_DRAG_AND_DROP', 'EPUB-, PDF- oder Kindle-Datei per Drag & Drop ablegen'),
       ('de', 'EBOOK_FILE_HOVER_INFO', '(Sicherungskopie, falls du deinen E-Reader verlierst)'),
       ('de', 'ONLY_EBOOK_FILES_ALLOWED', 'Nur EPUB-, PDF- oder Kindle-Dateien sind erlaubt'),
       ('de', 'PREVIEW_UNAVAILABLE', 'Vorschau nicht verfügbar'),
       ('de', 'FILE_TOO_LARGE', 'Die Datei ist zu groß (max. 100 MB)'),
       ('de', 'DOWNLOAD', 'Herunterladen'),
       ('de', 'FULLSCREEN', 'Vollbild'),
       ('de', 'EXIT_FULLSCREEN', 'Vollbild beenden'),
       ('de', 'SNACKBAR_BOOK_FILE_UPLOADED', 'E-Book-Datei hochgeladen'),
       ('de', 'SNACKBAR_BOOK_FILE_DELETED', 'E-Book-Datei gelöscht'),
       ('de', 'DELETE_FILE', 'Datei löschen '),
       ('de', 'DELETE_FILE_DESC', 'Möchtest du diese E-Book-Datei wirklich löschen?'),
       ('de', 'DELETE_CATEGORY', 'Kategorie löschen '),
       ('de', 'DELETE_CATEGORY_DESC', 'Möchtest du diese Kategorie wirklich entfernen?'),
       ('de', 'ADD_A_BOOK', 'Ein Buch hinzufügen'),
       ('de', 'REMOVE_BOOK', 'Buch entfernen'),
       ('de', 'REMOVE_BOOK_DESC', 'Möchtest du dieses Buch wirklich von diesem Kunden entfernen?'),
       ('de', 'EDIT_CUSTOMER', 'Kunde bearbeiten'),
       ('de', 'ADD_CUSTOMER', 'Kunde hinzufügen'),
       ('de', 'TOTAL_BOOKS', 'Bücher insgesamt'),
       ('de', 'DELETE_CUSTOMER', 'Kunde löschen '),
       ('de', 'DELETE_CUSTOMER_DESC', 'Möchtest du diesen Kunden wirklich entfernen?'),
       ('de', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Hinzugefügte Bücher im Zeitverlauf'),
       ('de', 'DASHBOARD_TOTAL', 'Gesamt'),
       ('de', 'RETURN_BOOKS', 'Bücher zurückgeben'),
       ('de', 'SNACKBAR_RETURN_BOOKS', 'Die Bücher wurden erfolgreich zurückgegeben'),
       ('de', 'RETURN', 'Zurückgeben'),
       ('de', 'DASHBOARD_CHART', 'Diagramm'),
       ('de', 'DASHBOARD_LAST_BOOKS', 'Letzte Bücher'),
       ('de', 'DASHBOARD_HERO_PREFIX', 'Du hast'),
       ('de', 'DASHBOARD_HERO_SUFFIX', 'neue Bücher diesen Monat'),
       ('de', 'DASHBOARD_ALL_CATEGORIES', 'Alle'),
       ('de', 'DASHBOARD_BROWSE_CATEGORIES', 'Nach Kategorie durchsuchen'),
       ('de', 'DASHBOARD_ON_LOAN', 'Derzeit ausgeliehen'),
       ('de', 'DASHBOARD_LOANED_TO', 'Ausgeliehen an'),
       ('de', 'DASHBOARD_NO_LOANS', 'Derzeit nichts ausgeliehen'),
       ('de', 'LOANS', 'Ausleihen'),
       ('de', 'LOANED_ON', 'Ausgeliehen am'),
       ('de', 'DATE_FROM', 'Von'),
       ('de', 'DATE_TO', 'Bis'),
       ('de', 'ALL_GROUPS', 'Alle Gruppen'),
       ('de', 'EMPTY_LOANS_TITLE', 'Keine Bücher ausgeliehen'),
       ('de', 'EMPTY_LOANS_DESC', 'Bücher, die derzeit an einen Kunden ausgeliehen sind, werden hier angezeigt.'),
       ('de', 'VIEW_ALL', 'Alle anzeigen'),
       ('de', 'DASHBOARD_LOANS_NOTE', 'Die 5 letzten Ausleihen werden angezeigt'),
       ('de', 'EDIT_LOCATION', 'Standort bearbeiten'),
       ('de', 'ADD_LOCATION', 'Standort hinzufügen'),
       ('de', 'DELETE_LOCATION', 'Standort löschen '),
       ('de', 'DELETE_LOCATION_DESC', 'Möchtest du diesen Standort wirklich entfernen?'),
       ('de', 'DEFAULT', 'Standard'),
       ('de', 'SET_AS_DEFAULT_LOCATION', 'Als Standardstandort festlegen'),
       ('de', 'NOT_FOUND_DESC', 'Die Seite wurde nicht gefunden.'),
       ('de', 'NOT_FOUND_GO_HOME', 'Zur Startseite'),
       ('de', 'ADD_BOOK_ISBN', 'Buch hinzufügen (ISBN)'),
       ('de', 'ADD_BOOK_ISBN_DESC', 'Füge deiner Bibliothek ganz einfach ein Buch hinzu, indem du seine ISBN eingibst. Die App ruft automatisch die Details des Buchs ab — Titel, Autor, Beschreibung und mehr — und fügt es nahtlos deiner Sammlung hinzu.'),
       ('de', 'ISBN_CODE', 'ISBN-Code'),
       ('de', 'INVALID_ISBN_CODE', 'Ungültiges ISBN-Format. Bitte gib eine gültige ISBN-10 oder ISBN-13 ein.'),
       ('de', 'ISBN_BOOK_NOT_FOUND', 'Buch nicht gefunden'),
       ('de', 'ISBN_ADD_ERROR', 'Fehler beim Hinzufügen des Buchs'),
       ('de', 'DRAG_AND_DROP_BOOK_COVER', 'Buchcover per Drag & Drop ablegen'),
       ('de', 'USERCONF_CHANGE_PASSWORD', 'Passwort ändern'),
       ('de', 'USERCONF_CURRENT_PASSWORD', 'Aktuelles Passwort'),
       ('de', 'USERCONF_NEW_PASSWORD', 'Neues Passwort'),
       ('de', 'USERCONF_MY_PROFILE', 'Mein Profil'),
       ('de', 'USERCONF_PASSWORD_SECURITY', 'Bitte füge alle erforderlichen Zeichen hinzu, um ein sicheres Passwort zu erstellen.'),
       ('de', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'Mindestens 8 Zeichen'),
       ('de', 'USERCONF_PASSWORD_UPPERCASE', 'Mindestens ein Großbuchstabe'),
       ('de', 'USERCONF_PASSWORD_ONE_NUMBER', 'Mindestens eine Zahl'),
       ('de', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'Mindestens ein Sonderzeichen'),
       ('de', 'USEERCONF_PASSWORD_REPEAT', 'Neues Passwort wiederholen'),
       ('de', 'USERCONF_PASSWORD_NOT_MATCH', 'Die Passwörter stimmen nicht überein!'),
       ('de', 'USERCONF_PASSWORD_CHANGED', 'Passwort erfolgreich geändert'),
       ('de', 'USERCONF_CHANGE_IMAGE', 'Bild ändern'),
       ('de', 'USERCONF_REMOVE_IMAGE', 'Bild entfernen'),
       ('de', 'USERCONF_IMAGE_SUPPORT', 'Es werden nur PNG- und JPG-Dateien unter 2 MB unterstützt'),
       ('de', 'USERCONF_NAME', 'Name'),
       ('de', 'USERCONF_LANGUAGE_REGION', 'Sprache und Region'),
       ('de', 'USERCONF_LANGUAGE', 'Sprache'),
       ('de', 'USERCONF_REGION', 'Region'),
       ('de', 'USERCONF_ACCOUNT_SECURITY', 'Kontosicherheit'),
       ('de', 'USERCONF_EMAIL', 'E-Mail'),
       ('de', 'USERCONF_EMAIL_DESC', 'Wird zum Anmelden und für Kontobenachrichtigungen verwendet.'),
       ('de', 'USERCONF_CHANGE_PASSWORD_DESC', 'Aktualisiere das Passwort deines Kontos, um es sicher zu halten. Du musst dein aktuelles Passwort eingeben und ein neues wählen, das die Sicherheitsanforderungen erfüllt.'),
       ('de', 'USERCONF_DELETE_DESC', 'Löscht das Konto endgültig und entfernt den Arbeitsbereich sowie die Bücher.'),
       ('de', 'USERCONF_DELETE', 'Konto löschen'),
       ('de', 'USERCONF_DELETE_USER_TITLE', 'Benutzer löschen'),
       ('de', 'USERCONF_DELETE_USER_DESC', 'Möchtest du dein Vaultisse-Konto wirklich löschen? Dadurch werden dein Konto und alle zugehörigen Inhalte endgültig entfernt.'),
       ('de', 'USERCONF_APPEARANCE', 'Erscheinungsbild'),
       ('de', 'USERCONF_THEME_BEIGE', 'Lesesaal'),
       ('de', 'USERCONF_THEME_BEIGE_DESC', 'Warm, hell und in Papiertönen.'),
       ('de', 'USERCONF_THEME_LIBRARY', 'Offenes Regal'),
       ('de', 'USERCONF_THEME_LIBRARY_DESC', 'Dunkel, in kühlen Tönen, angenehm für die Augen am Abend.'),
       ('de', 'USERCONF_COMPACT_MENU', 'Kompaktes Menü'),
       ('de', 'USERCONF_COMPACT_MENU_DESC', 'Reduziert die Seitenleiste auf reine Symbole und klappt sie beim Darüberfahren wieder aus.'),
       ('de', 'SNACKBAR_APPEARANCE_UPDATED', 'Erscheinungsbild aktualisiert'),
       ('de', 'USERCONF_FEATURES', 'Funktionen'),
       ('de', 'USERCONF_LEASING', 'Verleih'),
       ('de', 'USERCONF_LEASING_DESC', 'Behalte im Blick, wer was ausleiht. Aktiviert die Seiten Ausleihen und Kunden in der Seitenleiste.'),
       ('de', 'SNACKBAR_LEASING_UPDATED', 'Verleiheinstellung aktualisiert'),
       ('de', 'USERCONF_SESSIONS', 'Aktive Sitzungen'),
       ('de', 'USERCONF_SESSIONS_DESC', 'Geräte, die derzeit bei deinem Konto angemeldet sind.'),
       ('de', 'USERCONF_SESSIONS_EMPTY', 'Keine aktiven Sitzungen'),
       ('de', 'USERCONF_SESSION_CURRENT', 'Dieses Gerät'),
       ('de', 'USERCONF_SESSION_LOG_OUT', 'Abmelden'),
       ('de', 'USERCONF_SESSION_LAST_ACTIVE', 'Zuletzt aktiv'),
       ('de', 'USERCONF_SESSION_LOGOUT_TITLE', 'Dieses Gerät abmelden?'),
       ('de', 'USERCONF_SESSION_LOGOUT_DESC', 'Dieses Gerät wird sofort abgemeldet.'),
       ('de', 'SNACKBAR_SESSION_REVOKED', 'Gerät abgemeldet'),
       ('de', 'USERCONF_LOGIN_ACTIVITY', 'Letzte Anmeldungen'),
       ('de', 'USERCONF_LOGIN_ACTIVITY_DESC', 'Die letzten Anmeldungen bei deinem Konto.'),
       ('de', 'USERCONF_LOGIN_ACTIVITY_EMPTY', 'Noch keine Anmeldeaktivität'),
       ('de', 'ACTIVITY_LOGIN', 'Angemeldet'),
       ('de', 'ACTIVITY_LOGIN_FAILED', 'Fehlgeschlagener Anmeldeversuch'),
       ('de', 'ACTIVITY_LOGOUT', 'Abgemeldet'),
       ('de', 'ACTIVITY_PASSWORD_CHANGED', 'Passwort geändert'),
       ('de', 'DEVICE_UNKNOWN', 'Unbekanntes Gerät'),
       ('de', 'TWOFA_TITLE', 'Zwei-Faktor-Authentifizierung'),
       ('de', 'TWOFA_DESC', 'Erfordert beim Anmelden einen Code aus einer Authentifizierungs-App.'),
       ('de', 'TWOFA_STATUS_ENABLED', 'Aktiviert'),
       ('de', 'TWOFA_STATUS_DISABLED', 'Deaktiviert'),
       ('de', 'TWOFA_ENABLE', 'Aktivieren'),
       ('de', 'TWOFA_DISABLE', 'Deaktivieren'),
       ('de', 'TWOFA_SETUP_TITLE', 'Zwei-Faktor-Authentifizierung einrichten'),
       ('de', 'TWOFA_SETUP_SCAN_DESC', 'Scanne diesen QR-Code mit einer Authentifizierungs-App (Google Authenticator, Authy, 1Password, ...) und gib anschließend den angezeigten 6-stelligen Code ein.'),
       ('de', 'TWOFA_SETUP_MANUAL_KEY', 'Oder gib diesen Schlüssel manuell ein:'),
       ('de', 'TWOFA_CODE', 'Bestätigungscode'),
       ('de', 'TWOFA_INVALID_CODE', 'Ungültiger Code. Bitte versuche es erneut.'),
       ('de', 'TWOFA_BACKUP_CODES_TITLE', 'Speichere deine Backup-Codes'),
       ('de', 'TWOFA_BACKUP_CODES_DESC', 'Jeder Code kann einmal verwendet werden, um dich anzumelden, falls du den Zugriff auf deine Authentifizierungs-App verlierst. Bewahre sie an einem sicheren Ort auf - sie werden nicht erneut angezeigt.'),
       ('de', 'TWOFA_SAVED_CODES_CONFIRM', 'Ich habe diese Codes gespeichert'),
       ('de', 'TWOFA_DISABLE_TITLE', 'Zwei-Faktor-Authentifizierung deaktivieren'),
       ('de', 'TWOFA_DISABLE_DESC', 'Gib dein Passwort ein, um die Zwei-Faktor-Authentifizierung zu deaktivieren. Deine Backup-Codes funktionieren danach nicht mehr.'),
       ('de', 'TWOFA_DISABLE_PASSWORD', 'Passwort'),
       ('de', 'TWOFA_ENABLED_SNACKBAR', 'Zwei-Faktor-Authentifizierung aktiviert'),
       ('de', 'TWOFA_DISABLED_SNACKBAR', 'Zwei-Faktor-Authentifizierung deaktiviert'),
       ('de', 'USERCONF_IMAGE_FORMAT_ALERT', 'Bitte lade ein Bild im PNG- oder JPEG-Format hoch.'),
       ('de', 'EDIT_CATEGORY', 'Kategorie bearbeiten'),
       ('de', 'ADD_CATEGORY', 'Kategorie hinzufügen'),
       ('de', 'USERCONF_IMAGE_SIZE_ALERT', 'Die Dateigröße muss unter 2 MB liegen'),
       ('de', 'ADD_FILTER', 'Filter hinzufügen'),
       ('de', 'NO_STOCK_FILTER', 'Kein Bestand'),
       ('de', 'HAS_STOCK_FILTER', 'Mit Bestand'),
       ('de', 'ON_LOAN_FILTER', 'Ausgeliehen'),
       ('de', 'RECENT_FILTER', 'Neu'),
       ('de', 'UPLOAD_DATE_FILTER', 'Hinzufügedatum'),
       ('de', 'CATEGORY_FILTER', 'Kategorie'),
       ('de', 'ALL_CATEGORIES', 'Alle Kategorien'),
       ('de', 'GROUP_BY_CATEGORY', 'Nach Kategorie gruppieren'),
       ('de', 'UNCATEGORIZED', 'Ohne Kategorie'),
       ('de', 'WANT_TO_READ', 'Zu lesen'),
       ('de', 'CURRENTLY_READING', 'Wird gelesen'),
       ('de', 'READ', 'Gelesen'),
       ('de', 'READING_STATUS', 'Lesestatus'),
       ('de', 'DASHBOARD_TOTAL_READ', 'Gelesene Bücher'),
       ('de', 'DASHBOARD_NO_WANT_TO_READ', 'Deine Leseliste ist leer'),
       ('de', 'DASHBOARD_NO_CURRENTLY_READING', 'Du liest gerade nichts'),
       ('de', 'SORT_BY', 'Sortieren nach'),
       ('de', 'SORT_NAME_ASC', 'Name (A-Z)'),
       ('de', 'SORT_NAME_DESC', 'Name (Z-A)'),
       ('de', 'SORT_DATE_NEWEST', 'Neueste zuerst'),
       ('de', 'SORT_DATE_OLDEST', 'Älteste zuerst'),
       ('de', 'APPLY', 'Anwenden'),
       ('de', 'CLEAR', 'Zurücksetzen'),
       ('de', 'GROUPS', 'Gruppen'),
       ('de', 'GROUP', 'Gruppe'),
       ('de', 'NO_GROUP', 'Keine Gruppe'),
       ('de', 'NO_MEMBERS', 'Keine Mitglieder'),
       ('de', 'MANAGE_GROUPS', 'Gruppen verwalten'),
       ('de', 'ADD_GROUP', 'Gruppe hinzufügen'),
       ('de', 'EDIT_GROUP', 'Gruppe bearbeiten'),
       ('de', 'DELETE_GROUP', 'Gruppe löschen'),
       ('de', 'DELETE_GROUP_DESC', 'Möchtest du diese Gruppe wirklich entfernen? Die Kunden in dieser Gruppe werden dabei nicht gelöscht.'),
       ('de', 'GROUP_MEMBERS', 'Gruppenmitglieder'),
       ('de', 'ADD_MEMBERS_TO_GROUP', 'Mitglieder hinzufügen'),
       ('de', 'TOTAL_CUSTOMERS', 'Kunden'),
       ('de', 'SNACKBAR_NEW_GROUP_ADDED', 'Gruppe hinzugefügt'),
       ('de', 'SNACKBAR_GROUP_UPDATED', 'Gruppe aktualisiert'),
       ('de', 'SNACKBAR_DELETED_GROUP', 'Gruppe gelöscht'),
       ('de', 'MOVE_TO_GROUP', 'In Gruppe verschieben'),
       ('de', 'MOVE', 'Verschieben'),
       ('de', 'SELECTED', 'ausgewählt'),
       ('de', 'GROUPS_DRAG_DROP_HINT', 'Ziehe Kunden per Drag & Drop zwischen Gruppen, oder wähle mehrere aus, um sie auf einmal zu verschieben.'),
       ('de', 'EMPTY_LIBRARY_TITLE', 'Füge dein erstes Buch hinzu'),
       ('de', 'EMPTY_LIBRARY_DESC', 'Scanne eine ISBN oder füge ein Buch manuell hinzu, um deine Bibliothek aufzubauen.'),
       ('de', 'EMPTY_LOCATIONS_TITLE', 'Füge deinen ersten Standort hinzu'),
       ('de', 'EMPTY_LOCATIONS_DESC', 'Erstelle Regale, Räume oder Filialen, um zu organisieren, wo deine Bücher stehen.'),
       ('de', 'EMPTY_CUSTOMERS_TITLE', 'Füge deinen ersten Kunden hinzu'),
       ('de', 'EMPTY_CUSTOMERS_DESC', 'Füge Kunden hinzu, um mit dem Verleihen und Nachverfolgen deiner Bücher zu beginnen.'),
       ('de', 'EMPTY_CATEGORIES_TITLE', 'Füge deine erste Kategorie hinzu'),
       ('de', 'EMPTY_CATEGORIES_DESC', 'Erstelle Kategorien, um deine Bücher zu organisieren und einzuordnen.'),
       ('de', 'EMPTY_AUTHORS_TITLE', 'Füge deinen ersten Autor hinzu'),
       ('de', 'EMPTY_AUTHORS_DESC', 'Füge Autoren hinzu, um sie mit den Büchern in deiner Bibliothek zu verknüpfen.'),
       ('de', 'EMPTY_LAST_BOOKS_TITLE', 'Noch keine Bücher'),
       ('de', 'EMPTY_LAST_BOOKS_DESC', 'Bücher, die du hinzufügst, werden hier angezeigt.'),
       ('de', 'PUBLIC_INSTITUTION_SENSITIVE_DATA_WARNING', 'Dieses Konto ist als öffentliche Einrichtung registriert. Vermeide es, hier sensible persönliche Informationen einzugeben — verwende anstelle vollständiger Namen Schüler- oder Studentencodes bzw. IDs, die nur du zuordnen kannst.'),
       ('de', 'IMPORT', 'Importieren'),
       ('de', 'IMPORT_LIBRARY_DESC', 'Füge deiner Bibliothek über eine CSV-Datei in großer Zahl Bücher hinzu. Wähle die Herkunft der Datei aus und lade sie dann hoch — jede Zeile wird zu einem neuen Buch, und jedes Buch, das du bereits besitzt (erkannt anhand der ISBN oder, falls keine vorhanden ist, anhand des Titels), wird automatisch übersprungen.'),
       ('de', 'IMPORT_SELECT_ORIGIN', 'Importieren von'),
       ('de', 'IMPORT_ORIGIN_VAULTISSE', 'Vaultisse'),
       ('de', 'IMPORT_ORIGIN_VAULTISSE_DESC', 'Eine CSV-Datei nach Vaultisses eigener Vorlage'),
       ('de', 'IMPORT_ORIGIN_GOODREADS', 'Goodreads'),
       ('de', 'IMPORT_ORIGIN_GOODREADS_DESC', 'Deine aus Goodreads exportierte Bibliothek'),
       ('de', 'IMPORT_DROPZONE_TITLE', 'Klicke oder ziehe eine CSV-Datei per Drag & Drop hierher'),
       ('de', 'IMPORT_MAX_SIZE', 'Maximale Dateigröße: {maxSizeMb} MB'),
       ('de', 'IMPORT_FILE_TOO_LARGE', 'Diese Datei ist zu groß — die maximal zulässige Größe beträgt {maxSizeMb} MB'),
       ('de', 'IMPORT_ONLY_CSV_ALLOWED', 'Nur CSV-Dateien sind erlaubt'),
       ('de', 'IMPORT_DOWNLOAD_TEMPLATE', 'Vorlage herunterladen'),
       ('de', 'SNACKBAR_IMPORT_SUCCESS', 'Insgesamt importierte Bücher: {count}'),
       ('de', 'REMOVE', 'Entfernen'),
       ('de', 'VAULTS', 'Bibliotheken'),
       ('de', 'VAULTS_DESC', 'Eine Bibliothek kann mit anderen Personen geteilt werden. Wechsle zwischen den Bibliotheken, denen du angehörst, lade andere in deine ein und verwalte die Rollen der Mitglieder.'),
       ('de', 'VAULTS_EMPTY', 'Du gehörst noch keiner Bibliothek an'),
       ('de', 'VAULT_ACTIVE', 'Aktiv'),
       ('de', 'VAULT_SWITCH', 'Wechseln'),
       ('de', 'VAULT_MANAGE', 'Verwalten'),
       ('de', 'ADD_VAULT', 'Neue Bibliothek'),
       ('de', 'VAULT_SETTINGS', 'Einstellungen'),
       ('de', 'VAULT_INVITE', 'Einladungslink'),
       ('de', 'VAULT_INVITE_DESC', 'Jeder mit diesem Link kann darum bitten, dieser Bibliothek beizutreten. Du musst die Person freigeben, bevor sie etwas sehen oder hinzufügen kann.'),
       ('de', 'VAULT_MEMBERS', 'Mitglieder'),
       ('de', 'VAULT_YOU', 'Du'),
       ('de', 'VAULT_STATUS_PENDING', 'Ausstehend'),
       ('de', 'VAULT_STATUS_REJECTED', 'Abgelehnt'),
       ('de', 'VAULT_LEAVE', 'Verlassen'),
       ('de', 'VAULT_LEAVE_DESC', 'Möchtest du diese Bibliothek wirklich verlassen? Du verlierst den Zugriff auf ihre Bücher und Daten, es sei denn, du wirst erneut eingeladen.'),
       ('de', 'VAULT_REMOVE_MEMBER', 'Mitglied entfernen'),
       ('de', 'VAULT_REMOVE_MEMBER_DESC', 'Möchtest du {name} wirklich aus dieser Bibliothek entfernen?'),
       ('de', 'DELETE_VAULT', 'Bibliothek löschen'),
       ('de', 'DELETE_VAULT_DESC', 'Möchtest du diese Bibliothek wirklich löschen? Dies kann nicht rückgängig gemacht werden. Falls sie noch Bücher, Kunden oder andere Inhalte enthält, wirst du gebeten, diese zuerst in eine andere Bibliothek zu verschieben.'),
       ('de', 'VAULT_JOIN_REQUEST', 'Beitritt anfragen'),
       ('de', 'VAULT_JOIN_REQUESTED', 'Anfrage gesendet. Ein Mitglied mit der Berechtigung zur Mitgliederverwaltung muss sie genehmigen, bevor du auf diese Bibliothek zugreifen kannst.'),
       ('de', 'VAULT_JOIN_INVALID', 'Dieser Einladungslink ist ungültig oder abgelaufen.'),
       ('de', 'SNACKBAR_VAULT_CREATED', 'Bibliothek erfolgreich erstellt'),
       ('de', 'SNACKBAR_VAULT_UPDATED', 'Bibliothek erfolgreich aktualisiert'),
       ('de', 'SNACKBAR_VAULT_DELETED', 'Bibliothek erfolgreich gelöscht'),
       ('de', 'SNACKBAR_VAULT_SWITCHED', 'Aktive Bibliothek gewechselt'),
       ('de', 'SNACKBAR_VAULT_LEFT', 'Du hast die Bibliothek verlassen'),
       ('de', 'SNACKBAR_MEMBER_UPDATED', 'Mitglied erfolgreich aktualisiert'),
       ('de', 'SNACKBAR_MEMBER_REMOVED', 'Mitglied erfolgreich entfernt'),
       ('de', 'SNACKBAR_INVITE_LINK_COPIED', 'Einladungslink in die Zwischenablage kopiert'),
       ('de', 'BOOK_ADDED_BY', 'Hinzugefügt von'),
       ('de', 'VAULT_DELETE_ONLY_VAULT', 'Dies ist die einzige Bibliothek, der du angehörst - du kannst sie nicht löschen'),
       ('de', 'VAULT_TRANSFER_TITLE', 'Verschiebe zuerst den Inhalt'),
       ('de', 'VAULT_TRANSFER_DESC', 'Diese Bibliothek enthält noch Bücher, Kunden oder andere Inhalte. Wähle eine andere Bibliothek aus, in die alles verschoben werden soll, bevor du sie löschst.'),
       ('de', 'VAULT_TRANSFER_TARGET', 'Verschieben nach'),
       ('de', 'VAULT_TRANSFER_CONFIRM', 'Verschieben und löschen');
